/**
 * Schema Catalog - Static SSOT
 * 
 * Frozen at build time. No runtime registration.
 * 
 * @module schemas/catalog
 */

import type { CanonSchemaItem, SchemaCategory, SchemaId } from './types';

// Import all schemas
import { actionTypeSchema } from '../action';
import { auditLogEntrySchema } from '../audit';
import {
  auditLogIdSchema,
  batchIdSchema,
  entityIdSchema,
  mutationIdSchema,
  orgIdSchema,
  userIdSchema,
} from '../branded';
import {
  capabilityDomainSchema,
  capabilityKindSchema,
  capabilityNamespaceSchema,
} from '../capability';
import { entityRefSchema, entityTypeSchema } from '../entity';
import { apiResponseSchema } from '../envelope';
import { errorCodeSchema, kernelErrorSchema } from '../errors';
import { commonFields } from '../fields';
import { jsonValueSchema } from '../json-value';
import {
  assetKeyInputSchema,
  assetKeySchema,
  parsedAssetKeySchema,
  qualityRuleSchema,
} from '../lite-meta';
import { mutationSpecSchema } from '../mutation';
import { receiptSchema, receiptStatusSchema } from '../receipt';

/**
 * Frozen catalog of all Canon schemas
 * 
 * Initially hand-written, will be generated by: afena meta emit:schemas
 */
export const CANON_SCHEMAS: readonly CanonSchemaItem[] = Object.freeze([
  // ── Branded Schemas ──────────────────────────────────────
  {
    id: 'canon.branded.entityId',
    category: 'branded',
    name: 'entityId',
    version: 1,
    tags: ['core', 'identifier'],
    schema: entityIdSchema,
    meta: {
      title: 'Entity ID',
      description: 'Branded entity identifier (UUID)',
      examples: ['550e8400-e29b-41d4-a716-446655440000'],
      openapi: {
        title: 'EntityId',
        description: 'Unique entity identifier',
      },
    },
  },
  {
    id: 'canon.branded.orgId',
    category: 'branded',
    name: 'orgId',
    version: 1,
    tags: ['core', 'identifier'],
    schema: orgIdSchema,
    meta: {
      title: 'Organization ID',
      description: 'Branded organization identifier (UUID)',
      examples: ['660e8400-e29b-41d4-a716-446655440000'],
      openapi: {
        title: 'OrgId',
        description: 'Unique organization identifier',
      },
    },
  },
  {
    id: 'canon.branded.userId',
    category: 'branded',
    name: 'userId',
    version: 1,
    tags: ['core', 'identifier'],
    schema: userIdSchema,
    meta: {
      title: 'User ID',
      description: 'Branded user identifier (UUID)',
      examples: ['770e8400-e29b-41d4-a716-446655440000'],
      openapi: {
        title: 'UserId',
        description: 'Unique user identifier',
      },
    },
  },
  {
    id: 'canon.branded.batchId',
    category: 'branded',
    name: 'batchId',
    version: 1,
    tags: ['core', 'identifier'],
    schema: batchIdSchema,
    meta: {
      title: 'Batch ID',
      description: 'Branded batch identifier (UUID)',
      examples: ['880e8400-e29b-41d4-a716-446655440000'],
      openapi: {
        title: 'BatchId',
        description: 'Unique batch identifier',
      },
    },
  },
  {
    id: 'canon.branded.mutationId',
    category: 'branded',
    name: 'mutationId',
    version: 1,
    tags: ['core', 'identifier'],
    schema: mutationIdSchema,
    meta: {
      title: 'Mutation ID',
      description: 'Branded mutation identifier (UUID)',
      examples: ['990e8400-e29b-41d4-a716-446655440000'],
      openapi: {
        title: 'MutationId',
        description: 'Unique mutation identifier',
      },
    },
  },
  {
    id: 'canon.branded.auditLogId',
    category: 'branded',
    name: 'auditLogId',
    version: 1,
    tags: ['core', 'identifier', 'audit'],
    schema: auditLogIdSchema,
    meta: {
      title: 'Audit Log ID',
      description: 'Branded audit log identifier (UUID)',
      examples: ['aa0e8400-e29b-41d4-a716-446655440000'],
      openapi: {
        title: 'AuditLogId',
        description: 'Unique audit log identifier',
      },
    },
  },

  // ── Field Schemas ────────────────────────────────────────
  {
    id: 'canon.field.id',
    category: 'field',
    name: 'id',
    version: 1,
    tags: ['core', 'identifier'],
    schema: commonFields.id,
    meta: {
      title: 'ID',
      description: 'UUID identifier',
      examples: ['550e8400-e29b-41d4-a716-446655440000'],
    },
  },
  {
    id: 'canon.field.slug',
    category: 'field',
    name: 'slug',
    version: 1,
    tags: ['core'],
    schema: commonFields.slug,
    meta: {
      title: 'Slug',
      description: 'URL-friendly slug (lowercase alphanumeric with hyphens)',
      examples: ['my-entity-slug'],
    },
  },
  {
    id: 'canon.field.createdAt',
    category: 'field',
    name: 'createdAt',
    version: 1,
    tags: ['core', 'timestamp'],
    schema: commonFields.createdAt,
    meta: {
      title: 'Created At',
      description: 'Creation timestamp',
      examples: ['2024-01-01T00:00:00.000Z'],
    },
  },
  {
    id: 'canon.field.updatedAt',
    category: 'field',
    name: 'updatedAt',
    version: 1,
    tags: ['core', 'timestamp'],
    schema: commonFields.updatedAt,
    meta: {
      title: 'Updated At',
      description: 'Last update timestamp',
      examples: ['2024-01-01T00:00:00.000Z'],
    },
  },
  {
    id: 'canon.field.deletedAt',
    category: 'field',
    name: 'deletedAt',
    version: 1,
    tags: ['core', 'timestamp'],
    schema: commonFields.deletedAt,
    meta: {
      title: 'Deleted At',
      description: 'Deletion timestamp (null if not deleted)',
      examples: ['2024-01-01T00:00:00.000Z', null],
    },
  },
  {
    id: 'canon.field.version',
    category: 'field',
    name: 'version',
    version: 1,
    tags: ['core'],
    schema: commonFields.version,
    meta: {
      title: 'Version',
      description: 'Version number for optimistic locking',
      examples: [1, 2, 3],
    },
  },
  {
    id: 'canon.field.createdBy',
    category: 'field',
    name: 'createdBy',
    version: 1,
    tags: ['core', 'audit'],
    schema: commonFields.createdBy,
    meta: {
      title: 'Created By',
      description: 'User ID who created the record',
      examples: ['550e8400-e29b-41d4-a716-446655440000'],
    },
  },
  {
    id: 'canon.field.updatedBy',
    category: 'field',
    name: 'updatedBy',
    version: 1,
    tags: ['core', 'audit'],
    schema: commonFields.updatedBy,
    meta: {
      title: 'Updated By',
      description: 'User ID who last updated the record',
      examples: ['550e8400-e29b-41d4-a716-446655440000'],
    },
  },
  {
    id: 'canon.field.isDeleted',
    category: 'field',
    name: 'isDeleted',
    version: 1,
    tags: ['core'],
    schema: commonFields.isDeleted,
    meta: {
      title: 'Is Deleted',
      description: 'Soft delete flag',
      examples: [false, true],
    },
  },
  {
    id: 'canon.field.isActive',
    category: 'field',
    name: 'isActive',
    version: 1,
    tags: ['core'],
    schema: commonFields.isActive,
    meta: {
      title: 'Is Active',
      description: 'Active status flag',
      examples: [true, false],
    },
  },
  {
    id: 'canon.field.isArchived',
    category: 'field',
    name: 'isArchived',
    version: 1,
    tags: ['core'],
    schema: commonFields.isArchived,
    meta: {
      title: 'Is Archived',
      description: 'Archived status flag',
      examples: [false, true],
    },
  },
  {
    id: 'canon.field.limit',
    category: 'field',
    name: 'limit',
    version: 1,
    tags: ['core', 'pagination'],
    schema: commonFields.limit,
    meta: {
      title: 'Limit',
      description: 'Page size limit (1-100, default 20)',
      examples: [20, 50, 100],
    },
  },
  {
    id: 'canon.field.offset',
    category: 'field',
    name: 'offset',
    version: 1,
    tags: ['core', 'pagination'],
    schema: commonFields.offset,
    meta: {
      title: 'Offset',
      description: 'Page offset (0+, default 0)',
      examples: [0, 20, 40],
    },
  },
  {
    id: 'canon.field.cursor',
    category: 'field',
    name: 'cursor',
    version: 1,
    tags: ['core', 'pagination'],
    schema: commonFields.cursor,
    meta: {
      title: 'Cursor',
      description: 'Cursor for cursor-based pagination',
      examples: ['eyJpZCI6IjEyMyJ9'],
    },
  },

  // ── Entity Schemas ───────────────────────────────────────
  {
    id: 'canon.entity.entityType',
    category: 'entity',
    name: 'entityType',
    version: 1,
    tags: ['core'],
    schema: entityTypeSchema,
    meta: {
      title: 'Entity Type',
      description: 'Entity type identifier',
      examples: ['contacts', 'invoices'],
    },
  },
  {
    id: 'canon.entity.entityRef',
    category: 'entity',
    name: 'entityRef',
    version: 1,
    tags: ['core'],
    schema: entityRefSchema,
    meta: {
      title: 'Entity Reference',
      description: 'Reference to an entity (type + id)',
      examples: [{ type: 'contacts', id: '550e8400-e29b-41d4-a716-446655440000' }],
    },
  },

  // ── Validation Schemas ───────────────────────────────────
  {
    id: 'canon.validation.actionType',
    category: 'validation',
    name: 'actionType',
    version: 1,
    tags: ['core'],
    schema: actionTypeSchema,
    meta: {
      title: 'Action Type',
      description: 'Action type in format: entity.verb',
      examples: ['contacts.create', 'invoices.update'],
    },
  },
  {
    id: 'canon.validation.errorCode',
    category: 'validation',
    name: 'errorCode',
    version: 1,
    tags: ['core'],
    schema: errorCodeSchema,
    meta: {
      title: 'Error Code',
      description: 'Standardized error code',
      examples: ['VALIDATION_FAILED', 'NOT_FOUND'],
    },
  },
  {
    id: 'canon.validation.kernelError',
    category: 'validation',
    name: 'kernelError',
    version: 1,
    tags: ['core'],
    schema: kernelErrorSchema,
    meta: {
      title: 'Kernel Error',
      description: 'Kernel error object with code and message',
    },
  },
  {
    id: 'canon.validation.receiptStatus',
    category: 'validation',
    name: 'receiptStatus',
    version: 1,
    tags: ['core'],
    schema: receiptStatusSchema,
    meta: {
      title: 'Receipt Status',
      description: 'Mutation receipt status',
      examples: ['ok', 'rejected', 'error'],
    },
  },

  // ── API Schemas ──────────────────────────────────────────
  {
    id: 'canon.api.apiResponse',
    category: 'api',
    name: 'apiResponse',
    version: 1,
    tags: ['core'],
    schema: apiResponseSchema,
    meta: {
      title: 'API Response',
      description: 'Standard API response envelope',
    },
  },
  {
    id: 'canon.api.receipt',
    category: 'api',
    name: 'receipt',
    version: 1,
    tags: ['core'],
    schema: receiptSchema,
    meta: {
      title: 'Receipt',
      description: 'Mutation receipt',
    },
  },

  // ── Internal Schemas ─────────────────────────────────────
  {
    id: 'canon.internal.mutationSpec',
    category: 'internal',
    name: 'mutationSpec',
    version: 1,
    tags: ['core'],
    schema: mutationSpecSchema,
    meta: {
      title: 'Mutation Spec',
      description: 'Mutation specification',
    },
  },
  {
    id: 'canon.internal.jsonValue',
    category: 'internal',
    name: 'jsonValue',
    version: 1,
    tags: ['core'],
    schema: jsonValueSchema,
    meta: {
      title: 'JSON Value',
      description: 'JSON-serializable value',
    },
  },
  {
    id: 'canon.internal.auditLogEntry',
    category: 'internal',
    name: 'auditLogEntry',
    version: 1,
    tags: ['core', 'audit'],
    schema: auditLogEntrySchema,
    meta: {
      title: 'Audit Log Entry',
      description: 'Audit log entry',
    },
  },

  // ── Metadata Schemas ─────────────────────────────────────
  {
    id: 'canon.internal.assetKey',
    category: 'internal',
    name: 'assetKey',
    version: 1,
    tags: ['metadata'],
    schema: assetKeySchema,
    meta: {
      title: 'Asset Key',
      description: 'Canonical asset key (strict validation)',
      examples: ['db.rec.afenda.public.invoices', 'metric:revenue.monthly'],
      openapi: {
        title: 'AssetKey',
        description: 'Canonical asset key for metadata system',
      },
    },
  },
  {
    id: 'canon.internal.assetKeyInput',
    category: 'internal',
    name: 'assetKeyInput',
    version: 1,
    tags: ['metadata'],
    schema: assetKeyInputSchema,
    meta: {
      title: 'Asset Key Input',
      description: 'Asset key input with normalization',
      examples: ['DB.REC.AFENDA.PUBLIC.INVOICES', 'db.rec.afenda.public.invoices'],
    },
  },
  {
    id: 'canon.internal.parsedAssetKey',
    category: 'internal',
    name: 'parsedAssetKey',
    version: 1,
    tags: ['metadata'],
    schema: parsedAssetKeySchema,
    meta: {
      title: 'Parsed Asset Key',
      description: 'Parsed asset key with components',
    },
  },
  {
    id: 'canon.internal.qualityRule',
    category: 'internal',
    name: 'qualityRule',
    version: 1,
    tags: ['metadata'],
    schema: qualityRuleSchema,
    meta: {
      title: 'Quality Rule',
      description: 'Data quality rule definition',
    },
  },

  // ── Capability Schemas ───────────────────────────────────
  {
    id: 'canon.validation.capabilityKind',
    category: 'validation',
    name: 'capabilityKind',
    version: 1,
    tags: ['core'],
    schema: capabilityKindSchema,
    meta: {
      title: 'Capability Kind',
      description: 'Capability kind (read, write, admin, etc.)',
      examples: ['read', 'write', 'admin'],
    },
  },
  {
    id: 'canon.validation.capabilityDomain',
    category: 'validation',
    name: 'capabilityDomain',
    version: 1,
    tags: ['core'],
    schema: capabilityDomainSchema,
    meta: {
      title: 'Capability Domain',
      description: 'Capability domain (contacts, invoices, etc.)',
      examples: ['contacts', 'invoices', 'storage'],
    },
  },
  {
    id: 'canon.validation.capabilityNamespace',
    category: 'validation',
    name: 'capabilityNamespace',
    version: 1,
    tags: ['core'],
    schema: capabilityNamespaceSchema,
    meta: {
      title: 'Capability Namespace',
      description: 'Capability namespace (files, workflows, etc.)',
      examples: ['files', 'workflows', 'custom_fields'],
    },
  },
] as const);

/**
 * Frozen map for O(1) lookup
 */
export const CANON_SCHEMA_MAP: ReadonlyMap<SchemaId, CanonSchemaItem> = new Map(
  CANON_SCHEMAS.map((item) => [item.id, item] as const)
);

/**
 * Category index for fast filtering
 */
export const CANON_SCHEMA_BY_CATEGORY: Readonly<Record<SchemaCategory, readonly CanonSchemaItem[]>> = Object.freeze({
  branded: CANON_SCHEMAS.filter((s) => s.category === 'branded'),
  field: CANON_SCHEMAS.filter((s) => s.category === 'field'),
  entity: CANON_SCHEMAS.filter((s) => s.category === 'entity'),
  validation: CANON_SCHEMAS.filter((s) => s.category === 'validation'),
  api: CANON_SCHEMAS.filter((s) => s.category === 'api'),
  internal: CANON_SCHEMAS.filter((s) => s.category === 'internal'),
} as const);
