packages:
  - 'apps/*'
  - 'packages/*'
  - 'tools/*'

catalog:
  # ── Core ──────────────────────────────────────────────
  typescript: ~5.9.3
  '@types/node': ~20.19.33

  # ── React ─────────────────────────────────────────────
  react: ~19.2.3
  react-dom: ~19.2.3
  '@types/react': ~19.1.8
  '@types/react-dom': ~19.1.6

  # ── Next.js ───────────────────────────────────────────
  next: ~16.1.6
  eslint-config-next: ~16.1.6

  # ── ESLint ────────────────────────────────────────────
  eslint: ~9.39.2
  '@typescript-eslint/eslint-plugin': ~8.55.0
  '@typescript-eslint/parser': ~8.55.0
  eslint-config-prettier: ~9.1.2
  eslint-plugin-import: ~2.32.0
  eslint-plugin-jsx-a11y: ~6.10.2
  eslint-plugin-react: ~7.37.5
  eslint-plugin-react-hooks: ~5.2.0
  eslint-plugin-security: ~3.0.1

  # ── Build ─────────────────────────────────────────────
  tsup: ~8.5.1
  tsx: ~4.21.0
  turbo: ~2.8.3

  # ── Logging ───────────────────────────────────────────
  pino: ~10.3.1
  pino-abstract-transport: ~3.0.0
  pino-pretty: ~13.1.3

  # ── Formatting ────────────────────────────────────────
  prettier: ~3.8.1

  # ── Utilities ─────────────────────────────────────────
  rimraf: ~5.0.10
  openapi-typescript: ~6.7.6
  tslib: ~2.8.1
  clsx: ~2.1.1
  tailwind-merge: ~2.6.1
  tailwindcss: ~4.1.18
  '@tailwindcss/postcss': ~4.1.18
  postcss: ~8.5.6
  prettier-plugin-tailwindcss: ~0.7.2

  # ── Afena CLI deps ───────────────────────────────────
  commander: ~11.1.0
  cosmiconfig: ~8.3.6
  execa: ~5.1.1
  fast-glob: ~3.3.3
  listr2: ~3.14.0
  picocolors: ~1.1.1
  semver: ~7.6.3
  strip-ansi: ~6.0.1
  zod: ~3.24.0
  '@types/semver': ~7.5.8
