/**
 * Proposal command — generate PROPOSAL.md at monorepo root.
 *
 * Usage:
 *   afenda proposal gen [--dry-run] [--skip-validate]
 *   afenda proposal check
 */

import { safeExists, safeReadFile, safeWriteFile } from '../core/fs-safe';
import { findRepoRoot } from '../core/paths';
import { log } from '../core/logger';

import { analyzeProposal } from './analyzer';
import { renderProposalMd } from './templates';
import { runValidations } from '../project/validator';

const PROPOSAL_AUTOGEN_MARKER = '<!-- Generated by afenda proposal gen';

export interface ProposalGenOptions {
  repoRoot: string;
  dryRun?: boolean;
  skipValidate?: boolean;
  json?: boolean;
}

export interface ProposalGenResult {
  success: boolean;
  path: string;
  validations: Array<{ command: string; status: string; notes: string }>;
}

/**
 * Generate PROPOSAL.md at repo root.
 */
export async function runProposalGen(options: ProposalGenOptions): Promise<ProposalGenResult> {
  const { repoRoot, dryRun = false, skipValidate = false, json: jsonOutput = false } = options;

  if (!jsonOutput) log.bold('\n📜 Generating PROPOSAL.md\n');

  const validations = skipValidate
    ? []
    : await runValidations(repoRoot, { skipMeta: false, skipReadme: false, skipCatalog: false, skipDeps: false });

  if (!skipValidate && !jsonOutput) log.dim('  Validations complete.');

  const analysis = analyzeProposal(repoRoot, validations);
  const content = renderProposalMd(analysis);
  const path = `${repoRoot}/PROPOSAL.md`;

  if (dryRun && !jsonOutput) {
    log.info('  [dry-run] Would write PROPOSAL.md');
    log.dim(`  Size: ${content.length} chars`);
  }
  if (dryRun) {
    return {
      success: true,
      path,
      validations: validations.map((v) => ({ command: v.command, status: v.status, notes: v.notes })),
    };
  }

  safeWriteFile(repoRoot, content, 'PROPOSAL.md');
  if (!jsonOutput) log.success('  Wrote PROPOSAL.md');

  return {
    success: true,
    path,
    validations: validations.map((v) => ({ command: v.command, status: v.status, notes: v.notes })),
  };
}

/**
 * Validate PROPOSAL.md exists and has expected structure.
 */
export function validateProposal(repoRoot: string): string[] {
  const failures: string[] = [];

  if (!safeExists(repoRoot, 'PROPOSAL.md')) {
    failures.push('PROPOSAL.md does not exist');
    return failures;
  }

  const content = safeReadFile(repoRoot, 'PROPOSAL.md');

  if (!content.includes(PROPOSAL_AUTOGEN_MARKER)) {
    failures.push('PROPOSAL.md missing autogen marker — regenerate with: pnpm afenda proposal gen');
  }

  if (!content.includes('# Proposal:')) {
    failures.push('PROPOSAL.md missing expected heading');
  }

  return failures;
}

/**
 * Run proposal check. Returns true if validation passed.
 */
export function runProposalCheck(repoRoot: string): boolean {
  const failures = validateProposal(repoRoot);
  if (failures.length === 0) {
    log.success('PROPOSAL.md passes validation');
    return true;
  }
  for (const f of failures) {
    log.warn(f);
  }
  return false;
}

/**
 * Register proposal commands with the CLI program.
 */
export function registerProposalCommand(program: import('commander').Command): void {
  const proposalCmd = program
    .command('proposal')
    .description('Generate and validate PROPOSAL.md at monorepo root');

  proposalCmd
    .command('gen')
    .description('Generate PROPOSAL.md with rolling recommendations')
    .option('--dry-run', 'Preview without writing')
    .option('--skip-validate', 'Skip running validation commands (faster)')
    .option('--json', 'Output results as JSON')
    .action(async (opts: { dryRun?: boolean; skipValidate?: boolean; json?: boolean }) => {
      const repoRoot = findRepoRoot();
      const result = await runProposalGen({
        repoRoot,
        dryRun: opts.dryRun ?? false,
        skipValidate: opts.skipValidate ?? false,
        json: opts.json,
      });
      if (opts.json) log.json(result);
      if (!result.success) process.exitCode = 1;
    });

  proposalCmd
    .command('check')
    .description('Validate PROPOSAL.md exists and has expected structure')
    .action(() => {
      const repoRoot = findRepoRoot();
      const ok = runProposalCheck(repoRoot);
      if (!ok) process.exitCode = 1;
    });
}
