/**
 * PROPOSAL.md template — render proposal analysis as rolling recommendations.
 * Only shows recommendations for unresolved issues; no false positives.
 */

import type { ProposalAnalysis } from './analyzer';

const TEMPLATE_VERSION = 2;

export function renderProposalMd(analysis: ProposalAnalysis): string {
  const lines: string[] = [];
  const {
    projectAnalysis,
    failingValidations,
    hasOrphanedCapabilities,
    advisoryPackageExists,
    catalogCompliant,
    metaCheckPassed,
    advisoryRefCount,
  } = analysis;

  const domainCount = projectAnalysis.workspace.domainPackages.length;
  const coreCount = projectAnalysis.workspace.corePackages.length;

  lines.push('# Proposal: Rolling Architecture & CLI Improvements');
  lines.push('');
  lines.push('**Status:** Auto-generated recommendations');
  lines.push(`**Generated:** ${analysis.generatedAt} (via \`afenda proposal gen\`)`);
  lines.push('**Scope:** afenda CLI, architecture hygiene, performance, governance');
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## 1. Current State');
  lines.push('');
  lines.push(`- **Core packages:** ${coreCount}`);
  lines.push(`- **Domain packages:** ${domainCount}`);
  lines.push(`- **Validation failures:** ${failingValidations.length}`);
  const orphanedNote = hasOrphanedCapabilities
    ? metaCheckPassed === true
      ? 'Yes (accepted; meta check passed)'
      : 'Yes (see meta check)'
    : 'None';
  lines.push(`- **Orphaned capabilities:** ${orphanedNote}`);
  lines.push(`- **Advisory package:** ${advisoryPackageExists ? 'Present' : 'Removed (tables retained)'}`);
  if (!advisoryPackageExists && advisoryRefCount > 0) {
    lines.push(`- **Stale advisory refs:** ${advisoryRefCount} doc(s) need cleanup`);
  }
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## 2. Validation Gaps');
  lines.push('');

  if (failingValidations.length === 0) {
    lines.push('All validations passed. No immediate action required.');
  } else {
    lines.push('| Command | Status | Notes |');
    lines.push('|---------|--------|-------|');
    for (const v of failingValidations) {
      const notes = (v.notes ?? '').replace(/\|/g, '\\|').slice(0, 80);
      lines.push(`| \`${v.command}\` | ${v.status} | ${notes} |`);
    }
    lines.push('');
    lines.push('**Recommendation:** Fix failing validations before release. Run `pnpm afenda housekeeping` and `pnpm afenda meta check` for details.');
  }

  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## 3. Architecture Recommendations');
  lines.push('');
  const archRows: string[] = [];
  if (hasOrphanedCapabilities && metaCheckPassed === false) {
    archRows.push('| Capability coverage | High | Address orphaned capabilities via `afenda meta fix` or add exception |');
  }
  if (!advisoryPackageExists && advisoryRefCount > 0) {
    archRows.push('| Advisory refs | Low | Clean stale references from docs (`' + advisoryRefCount + '` files) |');
  } else if (!advisoryPackageExists) {
    archRows.push('| Advisory | Low | Database tables retained; remove from docs if not planned |');
  }
  if (catalogCompliant === false) {
    archRows.push('| Catalog protocol | Medium | Ensure all deps use `catalog:` in pnpm-workspace.yaml |');
  }
  if (archRows.length === 0) {
    lines.push('No outstanding architecture recommendations. Run `pnpm afenda proposal gen` without `--skip-validate` for full analysis.');
  } else {
    lines.push('| Area | Priority | Action |');
    lines.push('|------|----------|--------|');
    for (const row of archRows) lines.push(row);
  }
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## 4. Performance Recommendations');
  lines.push('');
  lines.push('| Area | Proposal |');
  lines.push('|------|----------|');
  lines.push('| meta:check | Cache enabled (AFENDA_META_NO_CACHE=1 to bypass) |');
  lines.push('| database DTS | Run `pnpm --filter afenda-database build:measure` to baseline |');
  lines.push('| Windows EPERM | observability/database use clean:!isWin |');
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## 5. Bundle Integration');
  lines.push('');
  lines.push('The `afenda bundle` command runs all primitives in order:');
  lines.push('');
  lines.push('1. **README** — `readme gen`');
  lines.push('2. **Meta** — capability checks');
  lines.push('3. **Housekeeping** — invariants');
  lines.push('4. **Proposal** — this document');
  lines.push('5. **Project** — PROJECT.md (last, aggregates all above)');
  lines.push('');
  lines.push('Use `--skip-project` or `--skip-proposal` to omit individual steps.');
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`<!-- Generated by afenda proposal gen (template v${TEMPLATE_VERSION}) — regenerate with: pnpm afenda proposal gen -->`);
  lines.push('');

  return lines.join('\n');
}
