#!/usr/bin/env node
/**
 * Quality Metrics Reporter
 * 
 * Generates various report formats:
 * - Markdown report for PRs and documentation
 * - JSON report for CI/CD integration
 * - HTML report for dashboard
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

interface QualityMetrics {
  timestamp: string;
  coverage: {
    lines: number;
    functions: number;
    branches: number;
    statements: number;
  };
  build: {
    duration: number;
    cacheHitRate: number;
    bundleSize: number;
  };
  codeQuality: {
    typeErrors: number;
    lintWarnings: number;
    lintErrors: number;
    todoCount: number;
    filesCount: number;
    linesOfCode: number;
  };
  git: {
    commitCount: number;
    contributors: number;
    lastCommitDate: string;
    filesChanged: number;
  };
}

function loadLatestMetrics(): QualityMetrics {
  const workspaceRoot = join(process.cwd(), '..', '..');
  const latestPath = join(workspaceRoot, '.quality-metrics', 'latest.json');
  
  if (!existsSync(latestPath)) {
    console.error('❌ No metrics found. Run `pnpm collect` first.');
    process.exit(1);
  }

  return JSON.parse(readFileSync(latestPath, 'utf-8'));
}

function generateMarkdownReport(metrics: QualityMetrics): string {
  const { coverage, build, codeQuality, git } = metrics;

  return `# 📊 Code Quality Report

**Generated:** ${new Date(metrics.timestamp).toLocaleString()}

## 🎯 Overview

| Metric | Value | Status |
|--------|-------|--------|
| **Test Coverage** | ${coverage.lines.toFixed(1)}% | ${coverage.lines >= 80 ? '✅' : '⚠️'} |
| **Type Errors** | ${codeQuality.typeErrors} | ${codeQuality.typeErrors === 0 ? '✅' : '❌'} |
| **Lint Errors** | ${codeQuality.lintErrors} | ${codeQuality.lintErrors === 0 ? '✅' : '❌'} |
| **Lint Warnings** | ${codeQuality.lintWarnings} | ${codeQuality.lintWarnings < 20 ? '✅' : '⚠️'} |
| **Build Time** | ${(build.duration / 1000).toFixed(1)}s | ${build.duration < 60000 ? '✅' : '⚠️'} |

## 📈 Coverage Breakdown

\`\`\`
Lines:      ${coverage.lines.toFixed(1)}%  ${'█'.repeat(Math.floor(coverage.lines / 5))}
Functions:  ${coverage.functions.toFixed(1)}%  ${'█'.repeat(Math.floor(coverage.functions / 5))}
Branches:   ${coverage.branches.toFixed(1)}%  ${'█'.repeat(Math.floor(coverage.branches / 5))}
Statements: ${coverage.statements.toFixed(1)}%  ${'█'.repeat(Math.floor(coverage.statements / 5))}
\`\`\`

## 🏗️ Build Performance

- **Build Duration:** ${(build.duration / 1000).toFixed(1)}s
- **Cache Hit Rate:** ${build.cacheHitRate.toFixed(1)}%
- **Bundle Size:** ${(build.bundleSize / 1024).toFixed(1)} KB

## 🔍 Code Quality

- **Source Files:** ${codeQuality.filesCount.toLocaleString()}
- **Lines of Code:** ${codeQuality.linesOfCode.toLocaleString()}
- **TODO/FIXME Count:** ${codeQuality.todoCount}
- **Type Errors:** ${codeQuality.typeErrors}
- **Lint Issues:** ${codeQuality.lintErrors} errors, ${codeQuality.lintWarnings} warnings

## 📝 Repository Activity

- **Total Commits:** ${git.commitCount}
- **Contributors:** ${git.contributors}
- **Files Changed (last 10 commits):** ${git.filesChanged}
- **Last Commit:** ${new Date(git.lastCommitDate).toLocaleString()}

## 🎯 Quality Thresholds

| Metric | Target | Current | Status |
|--------|--------|---------|--------|
| Line Coverage | ≥ 80% | ${coverage.lines.toFixed(1)}% | ${coverage.lines >= 80 ? '✅ Pass' : '❌ Fail'} |
| Branch Coverage | ≥ 75% | ${coverage.branches.toFixed(1)}% | ${coverage.branches >= 75 ? '✅ Pass' : '❌ Fail'} |
| Type Errors | 0 | ${codeQuality.typeErrors} | ${codeQuality.typeErrors === 0 ? '✅ Pass' : '❌ Fail'} |
| Lint Errors | 0 | ${codeQuality.lintErrors} | ${codeQuality.lintErrors === 0 ? '✅ Pass' : '❌ Fail'} |
| Build Time | < 60s | ${(build.duration / 1000).toFixed(1)}s | ${build.duration < 60000 ? '✅ Pass' : '⚠️ Warn'} |

---

*This report was automatically generated by the quality-metrics tool.*
`;
}

function generateJSONReport(metrics: QualityMetrics): string {
  return JSON.stringify(metrics, null, 2);
}

function generateHTMLReport(metrics: QualityMetrics): string {
  const { coverage, build, codeQuality, git } = metrics;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Quality Metrics Dashboard</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      padding: 2rem;
      min-height: 100vh;
    }
    .container {
      max-width: 1200px;
      margin: 0 auto;
      background: white;
      border-radius: 16px;
      box-shadow: 0 20px 60px rgba(0,0,0,0.3);
      overflow: hidden;
    }
    .header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 2rem;
      text-align: center;
    }
    .header h1 { font-size: 2rem; margin-bottom: 0.5rem; }
    .header p { opacity: 0.9; }
    .metrics {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
      gap: 1.5rem;
      padding: 2rem;
    }
    .metric-card {
      background: #f8fafc;
      border-radius: 12px;
      padding: 1.5rem;
      border-left: 4px solid #667eea;
    }
    .metric-card h3 {
      color: #334155;
      font-size: 0.875rem;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      margin-bottom: 0.5rem;
    }
    .metric-card .value {
      font-size: 2rem;
      font-weight: 700;
      color: #0f172a;
      margin-bottom: 0.25rem;
    }
    .metric-card .label {
      color: #64748b;
      font-size: 0.875rem;
    }
    .status { display: inline-block; padding: 0.25rem 0.75rem; border-radius: 9999px; font-size: 0.75rem; font-weight: 600; }
    .status.pass { background: #dcfce7; color: #166534; }
    .status.warn { background: #fef3c7; color: #92400e; }
    .status.fail { background: #fee2e2; color: #991b1b; }
    .progress-bar {
      height: 8px;
      background: #e2e8f0;
      border-radius: 9999px;
      overflow: hidden;
      margin-top: 0.5rem;
    }
    .progress-fill {
      height: 100%;
      background: linear-gradient(90deg, #667eea, #764ba2);
      transition: width 0.3s ease;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>📊 Quality Metrics Dashboard</h1>
      <p>Last updated: ${new Date(metrics.timestamp).toLocaleString()}</p>
    </div>
    
    <div class="metrics">
      <div class="metric-card">
        <h3>Test Coverage</h3>
        <div class="value">${coverage.lines.toFixed(1)}%</div>
        <div class="label">Lines covered</div>
        <div class="progress-bar">
          <div class="progress-fill" style="width: ${coverage.lines}%"></div>
        </div>
        <span class="status ${coverage.lines >= 80 ? 'pass' : 'warn'}">${coverage.lines >= 80 ? 'Pass' : 'Below Target'}</span>
      </div>

      <div class="metric-card">
        <h3>Type Safety</h3>
        <div class="value">${codeQuality.typeErrors}</div>
        <div class="label">TypeScript errors</div>
        <span class="status ${codeQuality.typeErrors === 0 ? 'pass' : 'fail'}">${codeQuality.typeErrors === 0 ? 'Pass' : 'Fail'}</span>
      </div>

      <div class="metric-card">
        <h3>Lint Quality</h3>
        <div class="value">${codeQuality.lintErrors}</div>
        <div class="label">Errors (${codeQuality.lintWarnings} warnings)</div>
        <span class="status ${codeQuality.lintErrors === 0 ? 'pass' : 'fail'}">${codeQuality.lintErrors === 0 ? 'Pass' : 'Fail'}</span>
      </div>

      <div class="metric-card">
        <h3>Build Time</h3>
        <div class="value">${(build.duration / 1000).toFixed(1)}s</div>
        <div class="label">Build duration</div>
        <span class="status ${build.duration < 60000 ? 'pass' : 'warn'}">${build.duration < 60000 ? 'Fast' : 'Slow'}</span>
      </div>

      <div class="metric-card">
        <h3>Cache Hit Rate</h3>
        <div class="value">${build.cacheHitRate.toFixed(1)}%</div>
        <div class="label">Turborepo cache</div>
        <div class="progress-bar">
          <div class="progress-fill" style="width: ${build.cacheHitRate}%"></div>
        </div>
      </div>

      <div class="metric-card">
        <h3>Code Size</h3>
        <div class="value">${codeQuality.linesOfCode.toLocaleString()}</div>
        <div class="label">Lines of code (${codeQuality.filesCount} files)</div>
      </div>

      <div class="metric-card">
        <h3>Technical Debt</h3>
        <div class="value">${codeQuality.todoCount}</div>
        <div class="label">TODO/FIXME comments</div>
        <span class="status ${codeQuality.todoCount < 50 ? 'pass' : 'warn'}">${codeQuality.todoCount < 50 ? 'Good' : 'Review'}</span>
      </div>

      <div class="metric-card">
        <h3>Repository Activity</h3>
        <div class="value">${git.contributors}</div>
        <div class="label">Contributors (${git.commitCount} commits)</div>
      </div>
    </div>
  </div>
</body>
</html>`;
}

async function main() {
  const format = process.argv[2] || 'markdown';
  const metrics = loadLatestMetrics();

  let report: string;
  let extension: string;

  switch (format) {
    case 'json':
      report = generateJSONReport(metrics);
      extension = 'json';
      break;
    case 'html':
      report = generateHTMLReport(metrics);
      extension = 'html';
      break;
    case 'markdown':
    default:
      report = generateMarkdownReport(metrics);
      extension = 'md';
      break;
  }

  const workspaceRoot = join(process.cwd(), '..', '..');
  const reportPath = join(workspaceRoot, '.quality-metrics', `report.${extension}`);
  writeFileSync(reportPath, report);

  console.log(`✅ ${format.toUpperCase()} report generated: ${reportPath}`);
  
  if (format === 'markdown') {
    console.log('\n' + report);
  }
}

main();
