/**
 * Project command — generate and validate PROJECT.md at monorepo root.
 *
 * Usage:
 *   afenda project gen [--dry-run] [--skip-validate]
 *   afenda project check
 */

import { safeExists, safeReadFile, safeWriteFile } from '../core/fs-safe';
import { findRepoRoot } from '../core/paths';
import { log } from '../core/logger';

import { analyzeProject } from './analyzer';
import { renderProjectMd } from './templates';
import { runValidations } from './validator';

const PROJECT_AUTOGEN_MARKER = '<!-- Generated by afenda project gen';

export interface ProjectGenOptions {
  repoRoot: string;
  dryRun?: boolean;
  skipValidate?: boolean;
  json?: boolean;
}

export interface ProjectGenResult {
  success: boolean;
  path: string;
  validations: Array<{ command: string; status: string; notes: string }>;
}

/**
 * Generate PROJECT.md at repo root.
 */
export async function runProjectGen(options: ProjectGenOptions): Promise<ProjectGenResult> {
  const { repoRoot, dryRun = false, skipValidate = false, json: jsonOutput = false } = options;

  if (!jsonOutput) log.bold('\n📋 Generating PROJECT.md\n');

  // 1. Analyze
  if (!jsonOutput) log.dim('  Analyzing workspace...');
  const analysis = analyzeProject(repoRoot);

  // 2. Run validations (unless skipped)
  const validations = skipValidate
    ? []
    : await runValidations(repoRoot, { skipMeta: false, skipReadme: false, skipCatalog: false, skipDeps: false });

  if (!skipValidate && !jsonOutput) log.dim('  Validations complete.');

  // 3. Render
  const content = renderProjectMd(analysis, validations);
  const path = `${repoRoot}/PROJECT.md`;

  if (dryRun && !jsonOutput) {
    log.info('  [dry-run] Would write PROJECT.md');
    log.dim(`  Size: ${content.length} chars`);
  }
  if (dryRun) {
    return {
      success: true,
      path,
      validations: validations.map((v) => ({ command: v.command, status: v.status, notes: v.notes })),
    };
  }

  safeWriteFile(repoRoot, content, 'PROJECT.md');
  if (!jsonOutput) log.success('  Wrote PROJECT.md');

  return {
    success: true,
    path,
    validations: validations.map((v) => ({ command: v.command, status: v.status, notes: v.notes })),
  };
}

/**
 * Validate PROJECT.md exists and has expected structure.
 */
export function validateProject(repoRoot: string): string[] {
  const failures: string[] = [];

  if (!safeExists(repoRoot, 'PROJECT.md')) {
    failures.push('PROJECT.md does not exist');
    return failures;
  }

  const content = safeReadFile(repoRoot, 'PROJECT.md');

  if (!content.includes(PROJECT_AUTOGEN_MARKER)) {
    failures.push('PROJECT.md missing autogen marker — regenerate with: pnpm afenda project gen');
  }

  if (!content.includes('# AFENDA-NEXUS — Project Analysis & Verdict')) {
    failures.push('PROJECT.md missing expected heading');
  }

  return failures;
}

/**
 * Run project check. Returns true if validation passed.
 */
export function runProjectCheck(repoRoot: string): boolean {
  const failures = validateProject(repoRoot);
  if (failures.length === 0) {
    log.success('PROJECT.md passes validation');
    return true;
  }
  for (const f of failures) {
    log.warn(f);
  }
  return false;
}

/**
 * Register project commands with the CLI program.
 */
export function registerProjectCommand(program: import('commander').Command): void {
  const projectCmd = program.command('project').description('Generate and validate PROJECT.md at monorepo root');

  projectCmd
    .command('gen')
    .description('Generate PROJECT.md with analysis and validation results')
    .option('--dry-run', 'Preview without writing')
    .option('--skip-validate', 'Skip running validation commands (faster)')
    .option('--json', 'Output results as JSON')
    .action(async (opts: { dryRun?: boolean; skipValidate?: boolean; json?: boolean }) => {
      const repoRoot = findRepoRoot();
      const result = await runProjectGen({
        repoRoot,
        dryRun: opts.dryRun ?? false,
        skipValidate: opts.skipValidate ?? false,
        json: opts.json,
      });
      if (opts.json) log.json(result);
      if (!result.success) process.exitCode = 1;
    });

  projectCmd
    .command('check')
    .description('Validate PROJECT.md exists and has expected structure')
    .action(() => {
      const repoRoot = findRepoRoot();
      const ok = runProjectCheck(repoRoot);
      if (!ok) process.exitCode = 1;
    });
}
