import { describe, it, expect } from 'vitest';
import { renderProjectMd } from './templates';
import type { ProjectAnalysis } from './analyzer';
import type { ValidationResult } from './validator';

function mkAnalysis(overrides?: Partial<ProjectAnalysis>): ProjectAnalysis {
  return {
    repoRoot: '/repo',
    generatedAt: '2025-01-01',
    workspace: {
      packages: ['packages/a', 'packages/b'],
      corePackages: ['packages/canon', 'packages/database'],
      domainPackages: ['business-domain/finance/accounting'],
      tools: ['tools/cli'],
      apps: ['apps/web'],
    },
    manifest: {
      tableCount: 100,
      totalFiles: 500,
      totalLoc: 50000,
      totalTestFiles: 80,
      totalTestLoc: 4000,
      packageCount: 20,
    },
    docsExist: { architecture: true, governance: true, businessDomain: true },
    ...overrides,
  };
}

describe('renderProjectMd', () => {
  it('includes expected heading', () => {
    const out = renderProjectMd(mkAnalysis(), []);
    expect(out).toContain('# AFENDA-NEXUS — Project Analysis & Verdict');
  });

  it('includes autogen marker', () => {
    const out = renderProjectMd(mkAnalysis(), []);
    expect(out).toContain('<!-- Generated by afenda project gen');
  });

  it('includes validation results section', () => {
    const validations: ValidationResult[] = [
      { command: 'housekeeping', status: 'pass', notes: 'Ok', exitCode: 0 },
      { command: 'meta:check', status: 'fail', notes: 'Failed', exitCode: 1 },
    ];
    const out = renderProjectMd(mkAnalysis(), validations);
    expect(out).toContain('## 12. Validation Results');
    expect(out).toContain('housekeeping');
    expect(out).toContain('meta:check');
  });

  it('uses manifest stats when present', () => {
    const out = renderProjectMd(
      mkAnalysis({ manifest: { tableCount: 50, totalFiles: 100, totalLoc: 10000, totalTestFiles: 10, totalTestLoc: 500, packageCount: 5 } }),
      [],
    );
    expect(out).toContain('50');
    expect(out).toContain('10k');
  });
});
