import { describe, it, expect, vi, beforeEach } from 'vitest';
import { validateProject } from './index';

vi.mock('../core/fs-safe', () => ({
  safeExists: vi.fn(),
  safeReadFile: vi.fn(),
}));

const { safeExists, safeReadFile } = await import('../core/fs-safe');

describe('validateProject', () => {
  const repoRoot = '/test';

  beforeEach(() => {
    vi.mocked(safeExists).mockReset();
    vi.mocked(safeReadFile).mockReset();
  });

  it('returns failure when PROJECT.md does not exist', () => {
    vi.mocked(safeExists).mockReturnValue(false);
    expect(validateProject(repoRoot)).toEqual(['PROJECT.md does not exist']);
  });

  it('returns failure when autogen marker missing', () => {
    vi.mocked(safeExists).mockReturnValue(true);
    vi.mocked(safeReadFile).mockReturnValue('# Other heading\n\nNo marker');
    expect(validateProject(repoRoot)).toContain(
      'PROJECT.md missing autogen marker — regenerate with: pnpm afenda project gen',
    );
  });

  it('returns failure when expected heading missing', () => {
    vi.mocked(safeExists).mockReturnValue(true);
    vi.mocked(safeReadFile).mockReturnValue(
      '<!-- Generated by afenda project gen -->\n\n# Wrong Heading',
    );
    expect(validateProject(repoRoot)).toContain('PROJECT.md missing expected heading');
  });

  it('returns empty array when valid', () => {
    vi.mocked(safeExists).mockReturnValue(true);
    vi.mocked(safeReadFile).mockReturnValue(
      '<!-- Generated by afenda project gen -->\n\n# AFENDA-NEXUS — Project Analysis & Verdict',
    );
    expect(validateProject(repoRoot)).toEqual([]);
  });
});
