/**
 * Type Compatibility Matrix
 *
 * Determines compatibility between Canon DataTypes for migration and transformation.
 *
 * Invariants (locked - see canon.architecture.md §8.3):
 * TC1: Self-compatibility (T → T is exact)
 * TC2: Symmetry (if A→B widening, then B→A narrowing or lossy)
 */

import type { DataType } from '../enums/data-types';

/**
 * Compatibility level between two types
 */
export type CompatLevel =
  | 'exact'
  | 'widening' // Compatible, loses no data (e.g., short_text → long_text)
  | 'narrowing' // Compatible, potential data loss (e.g., long_text → short_text)
  | 'lossy' // Very incompatible, significant data loss
  | 'incompatible'; // Cannot convert

/**
 * Type compatibility matrix (v1)
 * Read as: "From this type (row) to another type (column), what is the compatibility?"
 */
export const TYPE_COMPAT_MATRIX: Record<DataType, Record<DataType, CompatLevel>> = {
  // TC1 invariant: All diagonals are 'exact'
  short_text: {
    short_text: 'exact',
    long_text: 'widening',
    integer: 'narrowing',
    decimal: 'narrowing',
    money: 'narrowing',
    boolean: 'narrowing',
    date: 'narrowing',
    datetime: 'narrowing',
    enum: 'narrowing',
    multi_enum: 'incompatible',
    email: 'narrowing',
    phone: 'narrowing',
    url: 'narrowing',
    entity_ref: 'narrowing',
    json: 'widening',
    binary: 'incompatible',
    file: 'incompatible',
    single_select: 'narrowing',
    multi_select: 'incompatible',
    rich_text: 'widening',
    currency: 'narrowing',
    formula: 'incompatible',
    relation: 'incompatible',
  },

  long_text: {
    short_text: 'narrowing',
    long_text: 'exact',
    integer: 'narrowing',
    decimal: 'narrowing',
    money: 'narrowing',
    boolean: 'narrowing',
    date: 'narrowing',
    datetime: 'narrowing',
    enum: 'narrowing',
    multi_enum: 'narrowing',
    email: 'narrowing',
    phone: 'narrowing',
    url: 'narrowing',
    entity_ref: 'narrowing',
    json: 'widening',
    binary: 'incompatible',
    file: 'incompatible',
    single_select: 'narrowing',
    multi_select: 'incompatible',
    rich_text: 'exact',
    currency: 'narrowing',
    formula: 'incompatible',
    relation: 'incompatible',
  },

  integer: {
    short_text: 'widening',
    long_text: 'widening',
    integer: 'exact',
    decimal: 'widening',
    money: 'widening',
    boolean: 'narrowing',
    date: 'incompatible',
    datetime: 'incompatible',
    enum: 'narrowing',
    multi_enum: 'incompatible',
    email: 'widening',
    phone: 'widening',
    url: 'widening',
    entity_ref: 'narrowing',
    json: 'widening',
    binary: 'incompatible',
    file: 'incompatible',
    single_select: 'narrowing',
    multi_select: 'incompatible',
    rich_text: 'widening',
    currency: 'widening',
    formula: 'incompatible',
    relation: 'incompatible',
  },

  decimal: {
    short_text: 'widening',
    long_text: 'widening',
    integer: 'narrowing',
    decimal: 'exact',
    money: 'exact',
    boolean: 'narrowing',
    date: 'incompatible',
    datetime: 'incompatible',
    enum: 'narrowing',
    multi_enum: 'incompatible',
    email: 'widening',
    phone: 'widening',
    url: 'widening',
    entity_ref: 'narrowing',
    json: 'widening',
    binary: 'incompatible',
    file: 'incompatible',
    single_select: 'narrowing',
    multi_select: 'incompatible',
    rich_text: 'widening',
    currency: 'exact',
    formula: 'incompatible',
    relation: 'incompatible',
  },

  boolean: {
    short_text: 'widening',
    long_text: 'widening',
    integer: 'widening',
    decimal: 'widening',
    money: 'incompatible',
    boolean: 'exact',
    date: 'incompatible',
    datetime: 'incompatible',
    enum: 'narrowing',
    multi_enum: 'incompatible',
    email: 'widening',
    phone: 'widening',
    url: 'widening',
    entity_ref: 'incompatible',
    json: 'widening',
    binary: 'incompatible',
    file: 'incompatible',
    single_select: 'incompatible',
    multi_select: 'incompatible',
    rich_text: 'widening',
    currency: 'incompatible',
    formula: 'incompatible',
    relation: 'incompatible',
  },

  date: {
    short_text: 'widening',
    long_text: 'widening',
    integer: 'incompatible',
    decimal: 'incompatible',
    money: 'incompatible',
    boolean: 'incompatible',
    date: 'exact',
    datetime: 'widening',
    enum: 'widening',
    multi_enum: 'incompatible',
    email: 'widening',
    phone: 'widening',
    url: 'widening',
    entity_ref: 'incompatible',
    json: 'widening',
    binary: 'incompatible',
    file: 'incompatible',
    single_select: 'incompatible',
    multi_select: 'incompatible',
    rich_text: 'widening',
    currency: 'incompatible',
    formula: 'incompatible',
    relation: 'incompatible',
  },

  datetime: {
    short_text: 'widening',
    long_text: 'widening',
    integer: 'incompatible',
    decimal: 'incompatible',
    money: 'incompatible',
    boolean: 'incompatible',
    date: 'narrowing',
    datetime: 'exact',
    enum: 'widening',
    multi_enum: 'incompatible',
    email: 'widening',
    phone: 'widening',
    url: 'widening',
    entity_ref: 'incompatible',
    json: 'widening',
    binary: 'incompatible',
    file: 'incompatible',
    single_select: 'incompatible',
    multi_select: 'incompatible',
    rich_text: 'widening',
    currency: 'incompatible',
    formula: 'incompatible',
    relation: 'incompatible',
  },

  json: {
    short_text: 'narrowing',
    long_text: 'narrowing',
    integer: 'narrowing',
    decimal: 'narrowing',
    money: 'narrowing',
    boolean: 'narrowing',
    date: 'narrowing',
    datetime: 'narrowing',
    enum: 'narrowing',
    multi_enum: 'narrowing',
    email: 'narrowing',
    phone: 'narrowing',
    url: 'narrowing',
    entity_ref: 'narrowing',
    json: 'exact',
    binary: 'incompatible',
    file: 'incompatible',
    single_select: 'narrowing',
    multi_select: 'narrowing',
    rich_text: 'narrowing',
    currency: 'narrowing',
    formula: 'incompatible',
    relation: 'narrowing',
  },

  binary: {
    short_text: 'incompatible',
    long_text: 'incompatible',
    integer: 'incompatible',
    decimal: 'incompatible',
    money: 'incompatible',
    boolean: 'incompatible',
    date: 'incompatible',
    datetime: 'incompatible',
    enum: 'incompatible',
    multi_enum: 'incompatible',
    email: 'incompatible',
    phone: 'incompatible',
    url: 'incompatible',
    entity_ref: 'incompatible',
    json: 'incompatible',
    binary: 'exact',
    file: 'widening',
    single_select: 'incompatible',
    multi_select: 'incompatible',
    rich_text: 'incompatible',
    currency: 'incompatible',
    formula: 'incompatible',
    relation: 'incompatible',
  },

  entity_ref: {
    short_text: 'widening',
    long_text: 'widening',
    integer: 'widening',
    decimal: 'incompatible',
    money: 'incompatible',
    boolean: 'incompatible',
    date: 'incompatible',
    datetime: 'incompatible',
    enum: 'narrowing',
    multi_enum: 'incompatible',
    email: 'widening',
    phone: 'widening',
    url: 'widening',
    entity_ref: 'exact',
    json: 'widening',
    binary: 'incompatible',
    file: 'incompatible',
    single_select: 'incompatible',
    multi_select: 'incompatible',
    rich_text: 'widening',
    currency: 'incompatible',
    formula: 'incompatible',
    relation: 'narrowing',
  },

  file: {
    short_text: 'incompatible',
    long_text: 'incompatible',
    integer: 'incompatible',
    decimal: 'incompatible',
    money: 'incompatible',
    boolean: 'incompatible',
    date: 'incompatible',
    datetime: 'incompatible',
    enum: 'incompatible',
    multi_enum: 'incompatible',
    email: 'incompatible',
    phone: 'incompatible',
    url: 'incompatible',
    entity_ref: 'incompatible',
    json: 'incompatible',
    binary: 'narrowing',
    file: 'exact',
    single_select: 'incompatible',
    multi_select: 'incompatible',
    rich_text: 'incompatible',
    currency: 'incompatible',
    formula: 'incompatible',
    relation: 'incompatible',
  },

  single_select: {
    short_text: 'widening',
    long_text: 'widening',
    integer: 'widening',
    decimal: 'incompatible',
    money: 'incompatible',
    boolean: 'incompatible',
    date: 'incompatible',
    datetime: 'incompatible',
    enum: 'exact',
    multi_enum: 'widening',
    email: 'widening',
    phone: 'widening',
    url: 'widening',
    entity_ref: 'incompatible',
    json: 'widening',
    binary: 'incompatible',
    file: 'incompatible',
    single_select: 'exact',
    multi_select: 'widening',
    rich_text: 'widening',
    currency: 'incompatible',
    formula: 'incompatible',
    relation: 'incompatible',
  },

  multi_select: {
    short_text: 'widening',
    long_text: 'widening',
    integer: 'incompatible',
    decimal: 'incompatible',
    money: 'incompatible',
    boolean: 'incompatible',
    date: 'incompatible',
    datetime: 'incompatible',
    enum: 'narrowing',
    multi_enum: 'exact',
    email: 'widening',
    phone: 'widening',
    url: 'widening',
    entity_ref: 'incompatible',
    json: 'narrowing',
    binary: 'incompatible',
    file: 'incompatible',
    single_select: 'narrowing',
    multi_select: 'exact',
    rich_text: 'widening',
    currency: 'incompatible',
    formula: 'incompatible',
    relation: 'incompatible',
  },

  money: {
    short_text: 'widening',
    long_text: 'widening',
    integer: 'narrowing',
    decimal: 'exact',
    money: 'exact',
    boolean: 'incompatible',
    date: 'incompatible',
    datetime: 'incompatible',
    enum: 'narrowing',
    multi_enum: 'incompatible',
    email: 'widening',
    phone: 'widening',
    url: 'widening',
    entity_ref: 'narrowing',
    json: 'widening',
    binary: 'incompatible',
    file: 'incompatible',
    single_select: 'narrowing',
    multi_select: 'incompatible',
    rich_text: 'widening',
    currency: 'exact',
    formula: 'incompatible',
    relation: 'incompatible',
  },

  enum: {
    short_text: 'widening',
    long_text: 'widening',
    integer: 'widening',
    decimal: 'widening',
    money: 'widening',
    boolean: 'narrowing',
    date: 'narrowing',
    datetime: 'narrowing',
    enum: 'exact',
    multi_enum: 'narrowing',
    email: 'widening',
    phone: 'widening',
    url: 'widening',
    entity_ref: 'narrowing',
    json: 'widening',
    binary: 'incompatible',
    file: 'incompatible',
    single_select: 'narrowing',
    multi_select: 'narrowing',
    rich_text: 'widening',
    currency: 'widening',
    formula: 'incompatible',
    relation: 'incompatible',
  },

  multi_enum: {
    short_text: 'widening',
    long_text: 'widening',
    integer: 'incompatible',
    decimal: 'incompatible',
    money: 'incompatible',
    boolean: 'incompatible',
    date: 'incompatible',
    datetime: 'incompatible',
    enum: 'widening',
    multi_enum: 'exact',
    email: 'widening',
    phone: 'widening',
    url: 'widening',
    entity_ref: 'incompatible',
    json: 'narrowing',
    binary: 'incompatible',
    file: 'incompatible',
    single_select: 'widening',
    multi_select: 'narrowing',
    rich_text: 'widening',
    currency: 'incompatible',
    formula: 'incompatible',
    relation: 'incompatible',
  },

  email: {
    short_text: 'narrowing',
    long_text: 'narrowing',
    integer: 'narrowing',
    decimal: 'narrowing',
    money: 'narrowing',
    boolean: 'narrowing',
    date: 'narrowing',
    datetime: 'narrowing',
    enum: 'narrowing',
    multi_enum: 'narrowing',
    email: 'exact',
    phone: 'narrowing',
    url: 'exact',
    entity_ref: 'narrowing',
    json: 'widening',
    binary: 'incompatible',
    file: 'incompatible',
    single_select: 'narrowing',
    multi_select: 'narrowing',
    rich_text: 'widening',
    currency: 'incompatible',
    formula: 'incompatible',
    relation: 'incompatible',
  },

  phone: {
    short_text: 'narrowing',
    long_text: 'narrowing',
    integer: 'narrowing',
    decimal: 'incompatible',
    money: 'incompatible',
    boolean: 'incompatible',
    date: 'incompatible',
    datetime: 'incompatible',
    enum: 'narrowing',
    multi_enum: 'narrowing',
    email: 'narrowing',
    phone: 'exact',
    url: 'narrowing',
    entity_ref: 'narrowing',
    json: 'widening',
    binary: 'incompatible',
    file: 'incompatible',
    single_select: 'narrowing',
    multi_select: 'narrowing',
    rich_text: 'widening',
    currency: 'incompatible',
    formula: 'incompatible',
    relation: 'incompatible',
  },

  url: {
    short_text: 'narrowing',
    long_text: 'narrowing',
    integer: 'incompatible',
    decimal: 'incompatible',
    money: 'incompatible',
    boolean: 'incompatible',
    date: 'incompatible',
    datetime: 'incompatible',
    enum: 'narrowing',
    multi_enum: 'incompatible',
    email: 'exact',
    phone: 'narrowing',
    url: 'exact',
    entity_ref: 'incompatible',
    json: 'widening',
    binary: 'incompatible',
    file: 'incompatible',
    single_select: 'incompatible',
    multi_select: 'incompatible',
    rich_text: 'widening',
    currency: 'incompatible',
    formula: 'incompatible',
    relation: 'incompatible',
  },

  rich_text: {
    short_text: 'narrowing',
    long_text: 'narrowing',
    integer: 'incompatible',
    decimal: 'incompatible',
    money: 'incompatible',
    boolean: 'incompatible',
    date: 'incompatible',
    datetime: 'incompatible',
    enum: 'narrowing',
    multi_enum: 'narrowing',
    email: 'narrowing',
    phone: 'narrowing',
    url: 'narrowing',
    entity_ref: 'incompatible',
    json: 'widening',
    binary: 'incompatible',
    file: 'incompatible',
    single_select: 'incompatible',
    multi_select: 'incompatible',
    rich_text: 'exact',
    currency: 'incompatible',
    formula: 'incompatible',
    relation: 'incompatible',
  },

  currency: {
    short_text: 'widening',
    long_text: 'widening',
    integer: 'narrowing',
    decimal: 'exact',
    money: 'exact',
    boolean: 'incompatible',
    date: 'incompatible',
    datetime: 'incompatible',
    enum: 'widening',
    multi_enum: 'incompatible',
    email: 'widening',
    phone: 'widening',
    url: 'widening',
    entity_ref: 'incompatible',
    json: 'widening',
    binary: 'incompatible',
    file: 'incompatible',
    single_select: 'incompatible',
    multi_select: 'incompatible',
    rich_text: 'widening',
    currency: 'exact',
    formula: 'incompatible',
    relation: 'incompatible',
  },

  formula: {
    short_text: 'incompatible',
    long_text: 'incompatible',
    integer: 'incompatible',
    decimal: 'incompatible',
    money: 'incompatible',
    boolean: 'incompatible',
    date: 'incompatible',
    datetime: 'incompatible',
    enum: 'incompatible',
    multi_enum: 'incompatible',
    email: 'incompatible',
    phone: 'incompatible',
    url: 'incompatible',
    entity_ref: 'incompatible',
    json: 'incompatible',
    binary: 'incompatible',
    file: 'incompatible',
    single_select: 'incompatible',
    multi_select: 'incompatible',
    rich_text: 'incompatible',
    currency: 'incompatible',
    formula: 'exact',
    relation: 'incompatible',
  },

  relation: {
    short_text: 'incompatible',
    long_text: 'incompatible',
    integer: 'incompatible',
    decimal: 'incompatible',
    money: 'incompatible',
    boolean: 'incompatible',
    date: 'incompatible',
    datetime: 'incompatible',
    enum: 'incompatible',
    multi_enum: 'incompatible',
    email: 'incompatible',
    phone: 'incompatible',
    url: 'incompatible',
    entity_ref: 'widening',
    json: 'widening',
    binary: 'incompatible',
    file: 'incompatible',
    single_select: 'incompatible',
    multi_select: 'incompatible',
    rich_text: 'incompatible',
    currency: 'incompatible',
    formula: 'incompatible',
    relation: 'exact',
  },
};

/**
 * Get compatibility level between two types
 * TC1 invariant: getCompatLevel(T, T) === 'exact' for all T
 */
export function getCompatLevel(from: DataType, to: DataType): CompatLevel {
  return TYPE_COMPAT_MATRIX[from]?.[to] ?? 'incompatible';
}

/**
 * Check if two types are compatible (exact or widening)
 * Returns true if from can be safely widened/converted to 'to'
 */
export function isCompatible(from: DataType, to: DataType): boolean {
  const level = getCompatLevel(from, to);
  return level === 'exact' || level === 'widening';
}

/**
 * Check if conversion from one type to another requires transformation
 * Returns true if conversion loses data (narrowing or lossy)
 */
export function requiresTransform(from: DataType, to: DataType): boolean {
  const level = getCompatLevel(from, to);
  return level === 'narrowing' || level === 'lossy';
}
