/**
 * Dunning Notices Table
 *
 * Individual notices generated by a dunning run, one per customer per invoice.
 * Tracks escalation level and delivery status.
 *
 * ERPNext equivalent: items/rows within Dunning DocType.
 */
import { sql } from 'drizzle-orm';
import {
  check,
  date,
  index,
  integer,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

import { erpEntityColumns } from '../helpers/erp-entity';
import { currencyCodeStrict, moneyMinor } from '../helpers/field-types';
import { erpIndexes } from '../helpers/standard-indexes';

export const dunningNotices = pgTable(
  'dunning_notices',
  {
    ...erpEntityColumns,

    /** FK to dunning_runs */
    dunningRunId: uuid('dunning_run_id').notNull(),
    /** FK to customers */
    customerId: uuid('customer_id').notNull(),
    /** FK to supplier_invoices / AR invoices (nullable — run may cover whole balance) */
    invoiceId: uuid('invoice_id'),
    /** Escalation level: 1 = friendly, 2 = formal, 3 = final */
    noticeLevel: integer('notice_level').notNull(),
    /** Specific action for this level */
    actionType: text('action_type').notNull(),
    /** Amount outstanding at notice creation */
    amountOutstandingMinor: moneyMinor('amount_outstanding_minor'),
    /** Currency of outstanding amount */
    currencyCode: currencyCodeStrict('currency_code'),
    /** Original due date of the receivable */
    dueDate: date('due_date'),
    /** When the notice was actually sent */
    sentAt: timestamp('sent_at', { withTimezone: true }),
    /** Notice lifecycle */
    status: text('status').notNull().default('draft'),
    /** Freeform notes or resolution comments */
    notes: text('notes'),
  },
  (t) => [
    ...erpIndexes('dunning_notices', t),

    // Prevent duplicate notices for same customer+invoice within a run
    uniqueIndex('uq__dunning_notices__org_run_customer_invoice').on(
      t.orgId,
      t.dunningRunId,
      t.customerId,
      t.invoiceId,
    ),

    index('idx__dunning_notices__customer').on(t.orgId, t.customerId),
    index('idx__dunning_notices__run').on(t.orgId, t.dunningRunId),

    check('dunning_notices_valid_level', sql`notice_level BETWEEN 1 AND 3`),
    check(
      'dunning_notices_valid_action_type',
      sql`action_type IN ('friendly_reminder', 'formal_demand', 'final_notice', 'legal_notice')`,
    ),
    check(
      'dunning_notices_valid_status',
      sql`status IN ('draft', 'sent', 'acknowledged', 'resolved', 'escalated')`,
    ),
  ],
);

export type DunningNotice = typeof dunningNotices.$inferSelect;
export type NewDunningNotice = typeof dunningNotices.$inferInsert;
