CREATE TABLE "accounts_settings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"org_id" text DEFAULT (auth.require_org_id()) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" text DEFAULT (auth.user_id()) NOT NULL,
	"updated_by" text DEFAULT (auth.user_id()) NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"deleted_at" timestamp with time zone,
	"deleted_by" text,
	"custom_data" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"unlink_payment_on_cancellation_of_invoice" boolean DEFAULT false,
	"unlink_advance_payment_on_cancelation_of_order" boolean DEFAULT false,
	"book_asset_depreciation_entry_automatically" boolean DEFAULT false,
	"allow_cost_center_in_entry_of_bs_account" boolean DEFAULT false,
	"add_fin_year_in_abbr" boolean DEFAULT false,
	"determine_address_for_tax" text,
	"over_billing_allowance" numeric(18, 2),
	"role_allowed_to_over_bill" text,
	"credit_limit" numeric(18, 2),
	"bypass_credit_limit_check_at_sales_order" boolean DEFAULT false,
	"check_supplier_invoice_number_uniqueness" boolean DEFAULT false,
	"make_payment_via_journal_entry" boolean DEFAULT false,
	"unmap_current_account_balance_in_journal_entry" boolean DEFAULT false,
	"invoice_exchange_rate_revaluation" boolean DEFAULT false,
	"automatic_accounting_for_stock_settings" text,
	"acc_frozen_upto" text,
	"frozen_accounts_modifier" text,
	"enable_common_party_accounting" boolean DEFAULT false,
	"enable_discount_accounting" boolean DEFAULT false,
	"book_deferred_entries_based_on" text,
	"book_deferred_entries_via_journal_entry" boolean DEFAULT false,
	"submit_journal_entries_automatically" boolean DEFAULT false,
	"automatically_process_deferred_accounting" boolean DEFAULT false,
	"automatically_fetch_payment_terms" boolean DEFAULT false,
	"allow_multi_currency_invoices_against_single_party_account" boolean DEFAULT false,
	"post_gst_cess_via_journal_entry" boolean DEFAULT false,
	"round_off_payment_amount" boolean DEFAULT false,
	"report_settings_json" text,
	"enable_fuzzy_matching" boolean DEFAULT false,
	"party_matching_algorithm" text,
	"auto_reconcile_payments" boolean DEFAULT false,
	"close_accounting_period_on_period_closing_voucher" boolean DEFAULT false,
	"tax_id_status_details" text,
	"tax_id_validation_url" text,
	"deferred_accounting_based_on_invoice_date" boolean DEFAULT false,
	"period_closing_voucher_closing_date" text,
	"use_custom_cash_flow" boolean DEFAULT false,
	"allow_stale_exchange_rates" boolean DEFAULT false,
	"stale_exchange_rates_allowed_for" integer,
	CONSTRAINT "accounts_settings_org_id_id_pk" PRIMARY KEY("org_id","id"),
	CONSTRAINT "accounts_settings_org_singleton" UNIQUE("org_id"),
	CONSTRAINT "accounts_settings_org_not_empty" CHECK (org_id <> '')
);
--> statement-breakpoint
ALTER TABLE "accounts_settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "stock_settings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"org_id" text DEFAULT (auth.require_org_id()) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" text DEFAULT (auth.user_id()) NOT NULL,
	"updated_by" text DEFAULT (auth.user_id()) NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"deleted_at" timestamp with time zone,
	"deleted_by" text,
	"custom_data" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"item_naming_by" text,
	"item_group" text,
	"stock_uom" text,
	"allow_negative_stock" boolean DEFAULT false,
	"default_warehouse" text,
	"set_qty_in_transactions_based_on_serial_no_batch_no" boolean DEFAULT false,
	"automatically_set_serial_nos_based_on_fifo" boolean DEFAULT false,
	"validate_stock_on_save" boolean DEFAULT false,
	"auto_insert_price_list_rate_if_missing" boolean DEFAULT false,
	"allow_items_not_in_bom" boolean DEFAULT false,
	"show_barcode_field" boolean DEFAULT false,
	"convert_item_desc_to_clean_html" boolean DEFAULT false,
	"auto_indent" boolean DEFAULT false,
	"raise_stock_request_when_stock_reaches_reorder_level" boolean DEFAULT false,
	"notify_by_email_on_creation_of_automatic_material_request" boolean DEFAULT false,
	"raise_po_request_when_stock_reaches_reorder_level" boolean DEFAULT false,
	"freeze_stocks_older_than" integer,
	"role_allowed_to_create_edit_frozen_stock" text,
	"action_if_qty_after_transaction_is_zero" text,
	"action_if_accumulated_qty_is_zero" text,
	"sample_retention_warehouse" text,
	"default_valid_days" integer,
	"cleanup_email_notifications_sent_days_ago" integer,
	"enable_stock_entry_batch_auto_creation" boolean DEFAULT false,
	"disable_serial_no_batch_selector" boolean DEFAULT false,
	"do_not_update_serial_batch_on_creation_of_auto_bundle" boolean DEFAULT false,
	"valuation" text,
	"rm_cost_as_per_bom" boolean DEFAULT false,
	"exact_cost_revaluation_based_on_vouchers" boolean DEFAULT false,
	"allow_to_edit_rate_in_stock_entry" boolean DEFAULT false,
	"allow_over_delivery_billing" boolean DEFAULT false,
	"over_delivery_receipt_allowance" numeric(18, 2),
	"role_allowed_to_over_deliver_receive" text,
	"enable_batch_wise_stock_balances" boolean DEFAULT false,
	CONSTRAINT "stock_settings_org_id_id_pk" PRIMARY KEY("org_id","id"),
	CONSTRAINT "stock_settings_org_singleton" UNIQUE("org_id"),
	CONSTRAINT "stock_settings_org_not_empty" CHECK (org_id <> '')
);
--> statement-breakpoint
ALTER TABLE "stock_settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE INDEX "accounts_settings_org_created_id_idx" ON "accounts_settings" USING btree ("org_id","created_at" desc,"id" desc);--> statement-breakpoint
CREATE INDEX "stock_settings_org_created_id_idx" ON "stock_settings" USING btree ("org_id","created_at" desc,"id" desc);--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-select" ON "accounts_settings" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.org_id() = "accounts_settings"."org_id"));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-insert" ON "accounts_settings" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((select auth.org_id() = "accounts_settings"."org_id"));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-update" ON "accounts_settings" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select auth.org_id() = "accounts_settings"."org_id")) WITH CHECK ((select auth.org_id() = "accounts_settings"."org_id"));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-delete" ON "accounts_settings" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((select auth.org_id() = "accounts_settings"."org_id"));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-select" ON "stock_settings" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.org_id() = "stock_settings"."org_id"));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-insert" ON "stock_settings" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((select auth.org_id() = "stock_settings"."org_id"));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-update" ON "stock_settings" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select auth.org_id() = "stock_settings"."org_id")) WITH CHECK ((select auth.org_id() = "stock_settings"."org_id"));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-delete" ON "stock_settings" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((select auth.org_id() = "stock_settings"."org_id"));