CREATE TABLE "global_defaults" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"org_id" text DEFAULT (auth.require_org_id()) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" text DEFAULT (auth.user_id()) NOT NULL,
	"updated_by" text DEFAULT (auth.user_id()) NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"deleted_at" timestamp with time zone,
	"deleted_by" text,
	"custom_data" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"default_company" uuid,
	"country" uuid,
	"default_distance_unit" uuid,
	"default_currency" uuid,
	"hide_login_with_email_link" boolean DEFAULT false,
	"session_expiry" text,
	"session_expiry_mobile" text,
	"enable_two_factor_auth" boolean DEFAULT false,
	"bypass_restrict_ip_check_if_two_factor_auth" boolean DEFAULT false,
	"disable_system_update_notifications" boolean DEFAULT false,
	"disable_change_log_notification" boolean DEFAULT false,
	"disable_user_pass" boolean DEFAULT false,
	"allow_login_using_mobile_number" boolean DEFAULT false,
	"allow_login_using_user_name" boolean DEFAULT false,
	"allow_consecutive_login" boolean DEFAULT false,
	"allow_error_trackers" boolean DEFAULT false,
	"enable_password_policy" boolean DEFAULT false,
	"minimum_password_score" integer,
	"enable_letterhead_on_printing_language" boolean DEFAULT false,
	"allow_stale_exchange_rates" boolean DEFAULT false,
	"setup_complete" boolean DEFAULT false,
	"date_format" text,
	"time_format" text,
	"time_zone" text,
	"float_precision" integer,
	"currency_precision" integer,
	"number_format" text,
	"first_day_of_the_week" text,
	"default_letterhead" uuid,
	"default_print_format" text,
	"default_print_style" text,
	"default_workspace" text,
	"default_language" text,
	"rounding" text,
	"disable_rounded_total" boolean DEFAULT false,
	"disable_in_words" boolean DEFAULT false,
	CONSTRAINT "global_defaults_org_id_id_pk" PRIMARY KEY("org_id","id"),
	CONSTRAINT "global_defaults_org_singleton" UNIQUE("org_id"),
	CONSTRAINT "global_defaults_org_not_empty" CHECK (org_id <> '')
);
--> statement-breakpoint
ALTER TABLE "global_defaults" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE INDEX "global_defaults_org_created_id_idx" ON "global_defaults" USING btree ("org_id","created_at" desc,"id" desc);--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-select" ON "global_defaults" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.org_id() = "global_defaults"."org_id"));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-insert" ON "global_defaults" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((select auth.org_id() = "global_defaults"."org_id"));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-update" ON "global_defaults" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select auth.org_id() = "global_defaults"."org_id")) WITH CHECK ((select auth.org_id() = "global_defaults"."org_id"));--> statement-breakpoint
CREATE POLICY "crud-authenticated-policy-delete" ON "global_defaults" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((select auth.org_id() = "global_defaults"."org_id"));