import { z } from 'zod';

export const AccountsSettingsSchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  unlink_payment_on_cancellation_of_invoice: z.boolean().optional().default(true),
  unlink_advance_payment_on_cancelation_of_order: z.boolean().optional().default(true),
  delete_linked_ledger_entries: z.boolean().optional().default(false),
  enable_immutable_ledger: z.boolean().optional().default(false),
  check_supplier_invoice_uniqueness: z.boolean().optional().default(false),
  automatically_fetch_payment_terms: z.boolean().optional().default(false),
  enable_common_party_accounting: z.boolean().optional().default(false),
  allow_multi_currency_invoices_against_single_party_account: z.boolean().optional().default(false),
  confirm_before_resetting_posting_date: z.boolean().optional().default(true),
  enable_accounting_dimensions: z.boolean().optional().default(false),
  enable_discounts_and_margin: z.boolean().optional().default(false),
  merge_similar_account_heads: z.boolean().optional().default(false),
  book_deferred_entries_based_on: z.enum(['Days', 'Months']).optional().default('Days'),
  automatically_process_deferred_accounting_entry: z.boolean().optional().default(true),
  book_deferred_entries_via_journal_entry: z.boolean().optional().default(false),
  submit_journal_entries: z.boolean().optional().default(false),
  determine_address_tax_category_from: z.enum(['Billing Address', 'Shipping Address']).optional().default('Billing Address'),
  add_taxes_from_item_tax_template: z.boolean().optional().default(true),
  add_taxes_from_taxes_and_charges_template: z.boolean().optional().default(false),
  book_tax_discount_loss: z.boolean().optional().default(false),
  round_row_wise_tax: z.boolean().optional().default(false),
  show_inclusive_tax_in_print: z.boolean().optional().default(false),
  show_taxes_as_table_in_print: z.boolean().optional().default(false),
  show_payment_schedule_in_print: z.boolean().optional().default(false),
  maintain_same_internal_transaction_rate: z.boolean().optional().default(false),
  fetch_valuation_rate_for_internal_transaction: z.boolean().optional().default(false),
  maintain_same_rate_action: z.enum(['Stop', 'Warn']).optional().default('Stop'),
  role_to_override_stop_action: z.string().optional(),
  allow_stale: z.boolean().optional().default(true),
  allow_pegged_currencies_exchange_rates: z.boolean().optional().default(false),
  stale_days: z.number().int().optional().default(1),
  auto_reconcile_payments: z.boolean().optional().default(false),
  auto_reconciliation_job_trigger: z.number().int().optional().default(15),
  reconciliation_queue_size: z.number().int().optional().default(5),
  exchange_gain_loss_posting_date: z.enum(['Invoice', 'Payment', 'Reconciliation Date']).optional().default('Payment'),
  enable_loyalty_point_program: z.boolean().optional().default(false),
  over_billing_allowance: z.number().optional(),
  role_allowed_to_over_bill: z.string().optional(),
  credit_controller: z.string().optional(),
  make_payment_via_journal_entry: z.boolean().optional().default(false),
  calculate_depr_using_total_days: z.boolean().optional().default(false),
  book_asset_depreciation_entry_automatically: z.boolean().optional().default(true),
  role_to_notify_on_depreciation_failure: z.string().optional(),
  ignore_account_closing_balance: z.boolean().optional().default(false),
  use_legacy_controller_for_pcv: z.boolean().optional().default(true),
  general_ledger_remarks_length: z.number().int().optional().default(0),
  receivable_payable_remarks_length: z.number().int().optional().default(0),
  receivable_payable_fetch_method: z.enum(['Buffered Cursor', 'UnBuffered Cursor', 'Raw SQL']).optional().default('Buffered Cursor'),
  default_ageing_range: z.string().optional().default('30, 60, 90, 120'),
  ignore_is_opening_check_for_reporting: z.boolean().optional().default(false),
  show_balance_in_coa: z.boolean().optional().default(true),
  enable_party_matching: z.boolean().optional().default(false),
  enable_fuzzy_matching: z.boolean().optional().default(false),
  create_pr_in_draft_status: z.boolean().optional().default(true),
  use_legacy_budget_controller: z.boolean().optional().default(false),
});

export type AccountsSettings = z.infer<typeof AccountsSettingsSchema>;

export const AccountsSettingsInsertSchema = AccountsSettingsSchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type AccountsSettingsInsert = z.infer<typeof AccountsSettingsInsertSchema>;
