import { z } from 'zod';

export const AssetSchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  docstatus: z.number().default(0),
  naming_series: z.enum(['ACC-ASS-.YYYY.-']).optional(),
  company: z.string(),
  item_code: z.string(),
  item_name: z.string().optional(),
  asset_name: z.string(),
  image: z.string().optional(),
  location: z.string(),
  asset_category: z.string().optional(),
  asset_type: z.enum(['Existing Asset', 'Composite Asset', 'Composite Component']).optional(),
  maintenance_required: z.boolean().optional().default(false),
  calculate_depreciation: z.boolean().optional().default(false),
  purchase_receipt: z.string().optional(),
  purchase_receipt_item: z.string().optional(),
  purchase_invoice: z.string().optional(),
  purchase_invoice_item: z.string().optional(),
  purchase_date: z.string(),
  available_for_use_date: z.string().optional(),
  disposal_date: z.string().optional(),
  net_purchase_amount: z.number().optional(),
  purchase_amount: z.number().optional(),
  asset_quantity: z.number().int().optional().default(1),
  additional_asset_cost: z.number().optional().default(0),
  total_asset_cost: z.number().optional(),
  opening_accumulated_depreciation: z.number().optional(),
  is_fully_depreciated: z.boolean().optional().default(false),
  opening_number_of_booked_depreciations: z.number().int().optional(),
  finance_books: z.array(z.unknown()).optional(),
  depreciation_method: z.enum(['Straight Line', 'Double Declining Balance', 'Written Down Value', 'Manual']).optional(),
  value_after_depreciation: z.number().optional(),
  frequency_of_depreciation: z.number().int().optional(),
  next_depreciation_date: z.string().optional(),
  total_number_of_depreciations: z.number().int().optional(),
  depreciation_schedule_view: z.string().optional(),
  cost_center: z.string().optional(),
  asset_owner: z.enum(['Company', 'Supplier', 'Customer']).optional().default('Company'),
  asset_owner_company: z.string().optional(),
  customer: z.string().optional(),
  supplier: z.string().optional(),
  policy_number: z.string().optional(),
  insurer: z.string().optional(),
  insured_value: z.string().optional(),
  insurance_start_date: z.string().optional(),
  insurance_end_date: z.string().optional(),
  comprehensive_insurance: z.string().optional(),
  status: z.enum(['Draft', 'Submitted', 'Cancelled', 'Partially Depreciated', 'Fully Depreciated', 'Sold', 'Scrapped', 'In Maintenance', 'Out of Order', 'Issue', 'Receipt', 'Capitalized', 'Work In Progress']).optional().default('Draft'),
  custodian: z.string().optional(),
  department: z.string().optional(),
  default_finance_book: z.string().optional(),
  depr_entry_posting_status: z.enum(['Successful', 'Failed']).optional(),
  journal_entry_for_scrap: z.string().optional(),
  split_from: z.string().optional(),
  amended_from: z.string().optional(),
  booked_fixed_asset: z.boolean().optional().default(false),
});

export type Asset = z.infer<typeof AssetSchema>;

export const AssetInsertSchema = AssetSchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type AssetInsert = z.infer<typeof AssetInsertSchema>;
