import { z } from 'zod';

export const BomSchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  docstatus: z.number().default(0),
  item: z.string(),
  company: z.string(),
  uom: z.string().optional(),
  quantity: z.number().default(1),
  is_active: z.boolean().optional().default(true),
  is_default: z.boolean().optional().default(true),
  allow_alternative_item: z.boolean().optional().default(false),
  set_rate_of_sub_assembly_item_based_on_bom: z.boolean().optional().default(true),
  is_phantom_bom: z.boolean().optional().default(false),
  project: z.string().optional(),
  image: z.string().optional(),
  rm_cost_as_per: z.enum(['Valuation Rate', 'Last Purchase Rate', 'Price List']).optional().default('Valuation Rate'),
  buying_price_list: z.string().optional(),
  price_list_currency: z.string().optional(),
  plc_conversion_rate: z.number().optional(),
  currency: z.string(),
  conversion_rate: z.number().default(1),
  with_operations: z.boolean().optional().default(false),
  track_semi_finished_goods: z.boolean().optional().default(false),
  transfer_material_against: z.enum(['Work Order', 'Job Card']).optional().default('Work Order'),
  routing: z.string().optional(),
  fg_based_operating_cost: z.boolean().optional().default(false),
  default_source_warehouse: z.string().optional(),
  default_target_warehouse: z.string().optional(),
  operating_cost_per_bom_quantity: z.number().optional(),
  operations: z.array(z.unknown()).optional(),
  items: z.array(z.unknown()),
  scrap_items: z.array(z.unknown()).optional(),
  process_loss_percentage: z.number().optional(),
  process_loss_qty: z.number().optional(),
  operating_cost: z.number().optional(),
  raw_material_cost: z.number().optional(),
  scrap_material_cost: z.number().optional(),
  base_operating_cost: z.number().optional(),
  base_raw_material_cost: z.number().optional(),
  base_scrap_material_cost: z.number().optional(),
  total_cost: z.number().optional(),
  base_total_cost: z.number().optional(),
  item_name: z.string().optional(),
  description: z.string().optional(),
  has_variants: z.boolean().optional().default(false),
  inspection_required: z.boolean().optional().default(false),
  quality_inspection_template: z.string().optional(),
  exploded_items: z.array(z.unknown()).optional(),
  show_in_website: z.boolean().optional().default(false),
  route: z.string().optional(),
  website_image: z.string().optional(),
  thumbnail: z.string().optional(),
  show_items: z.boolean().optional().default(false),
  show_operations: z.boolean().optional().default(false),
  web_long_description: z.string().optional(),
  bom_creator: z.string().optional(),
  bom_creator_item: z.string().optional(),
  amended_from: z.string().optional(),
});

export type Bom = z.infer<typeof BomSchema>;

export const BomInsertSchema = BomSchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type BomInsert = z.infer<typeof BomInsertSchema>;
