import { z } from 'zod';

export const CompanySchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  company_name: z.string(),
  abbr: z.string(),
  default_currency: z.string(),
  country: z.string(),
  is_group: z.boolean().optional().default(false),
  default_holiday_list: z.string().optional(),
  default_letter_head: z.string().optional(),
  tax_id: z.string().optional(),
  domain: z.string().optional(),
  date_of_establishment: z.string().optional(),
  parent_company: z.string().optional(),
  reporting_currency: z.string().optional(),
  company_logo: z.string().optional(),
  date_of_incorporation: z.string().optional(),
  phone_no: z.string().optional(),
  email: z.string().email().optional(),
  company_description: z.string().optional(),
  date_of_commencement: z.string().optional(),
  fax: z.string().optional(),
  website: z.string().optional(),
  address_html: z.string().optional(),
  registration_details: z.string().optional(),
  lft: z.number().int().optional(),
  rgt: z.number().int().optional(),
  old_parent: z.string().optional(),
  create_chart_of_accounts_based_on: z.enum(['Standard Template', 'Existing Company']).optional(),
  existing_company: z.string().optional(),
  chart_of_accounts: z.string().optional(),
  default_bank_account: z.string().optional(),
  default_cash_account: z.string().optional(),
  default_receivable_account: z.string().optional(),
  default_payable_account: z.string().optional(),
  write_off_account: z.string().optional(),
  unrealized_profit_loss_account: z.string().optional(),
  allow_account_creation_against_child_company: z.boolean().optional().default(false),
  default_expense_account: z.string().optional(),
  default_income_account: z.string().optional(),
  default_discount_account: z.string().optional(),
  payment_terms: z.string().optional(),
  cost_center: z.string().optional(),
  default_finance_book: z.string().optional(),
  exchange_gain_loss_account: z.string().optional(),
  unrealized_exchange_gain_loss_account: z.string().optional(),
  round_off_account: z.string().optional(),
  round_off_cost_center: z.string().optional(),
  round_off_for_opening: z.string().optional(),
  default_deferred_revenue_account: z.string().optional(),
  default_deferred_expense_account: z.string().optional(),
  book_advance_payments_in_separate_party_account: z.boolean().optional().default(false),
  reconcile_on_advance_payment_date: z.boolean().optional().default(false),
  reconciliation_takes_effect_on: z.enum(['Advance Payment Date', 'Oldest Of Invoice Or Advance', 'Reconciliation Date']).optional().default('Oldest Of Invoice Or Advance'),
  default_advance_received_account: z.string().optional(),
  default_advance_paid_account: z.string().optional(),
  auto_exchange_rate_revaluation: z.boolean().optional().default(false),
  auto_err_frequency: z.enum(['Daily', 'Weekly', 'Monthly']).optional(),
  submit_err_jv: z.boolean().optional().default(false),
  exception_budget_approver_role: z.string().optional(),
  accumulated_depreciation_account: z.string().optional(),
  depreciation_expense_account: z.string().optional(),
  series_for_depreciation_entry: z.string().optional(),
  disposal_account: z.string().optional(),
  depreciation_cost_center: z.string().optional(),
  capital_work_in_progress_account: z.string().optional(),
  asset_received_but_not_billed: z.string().optional(),
  accounts_frozen_till_date: z.string().optional(),
  role_allowed_for_frozen_entries: z.string().optional(),
  default_buying_terms: z.string().optional(),
  sales_monthly_history: z.string().optional(),
  monthly_sales_target: z.number().optional(),
  total_monthly_sales: z.number().optional(),
  default_selling_terms: z.string().optional(),
  default_sales_contact: z.string().optional(),
  default_warehouse_for_sales_return: z.string().optional(),
  credit_limit: z.number().optional(),
  transactions_annual_history: z.string().optional(),
  purchase_expense_account: z.string().optional(),
  service_expense_account: z.string().optional(),
  purchase_expense_contra_account: z.string().optional(),
  enable_perpetual_inventory: z.boolean().optional().default(true),
  enable_item_wise_inventory_account: z.boolean().optional().default(false),
  enable_provisional_accounting_for_non_stock_items: z.boolean().optional().default(false),
  default_inventory_account: z.string().optional(),
  valuation_method: z.enum(['FIFO', 'Moving Average', 'LIFO']).default('FIFO'),
  stock_adjustment_account: z.string().optional(),
  stock_received_but_not_billed: z.string().optional(),
  default_provisional_account: z.string().optional(),
  default_in_transit_warehouse: z.string().optional(),
  default_operating_cost_account: z.string().optional(),
  default_wip_warehouse: z.string().optional(),
  default_fg_warehouse: z.string().optional(),
  default_scrap_warehouse: z.string().optional(),
});

export type Company = z.infer<typeof CompanySchema>;

export const CompanyInsertSchema = CompanySchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type CompanyInsert = z.infer<typeof CompanyInsertSchema>;
