import { z } from 'zod';

export const CustomerSchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  naming_series: z.enum(['CUST-.YYYY.-']).optional(),
  customer_type: z.enum(['Company', 'Individual', 'Partnership']).default('Company'),
  customer_name: z.string(),
  gender: z.string().optional(),
  customer_group: z.string().optional(),
  territory: z.string().optional(),
  image: z.string().optional(),
  default_currency: z.string().optional(),
  default_bank_account: z.string().optional(),
  default_price_list: z.string().optional(),
  address_html: z.string().optional(),
  contact_html: z.string().optional(),
  customer_primary_address: z.string().optional(),
  primary_address: z.string().optional(),
  customer_primary_contact: z.string().optional(),
  mobile_no: z.string().optional(),
  email_id: z.string().optional(),
  first_name: z.string().optional(),
  last_name: z.string().optional(),
  tax_id: z.string().optional(),
  tax_category: z.string().optional(),
  tax_withholding_category: z.string().optional(),
  tax_withholding_group: z.string().optional(),
  accounts: z.array(z.unknown()).optional(),
  payment_terms: z.string().optional(),
  credit_limits: z.array(z.unknown()).optional(),
  is_internal_customer: z.boolean().optional().default(false),
  represents_company: z.string().optional(),
  companies: z.array(z.unknown()).optional(),
  loyalty_program: z.string().optional(),
  loyalty_program_tier: z.string().optional(),
  account_manager: z.string().optional(),
  sales_team: z.array(z.unknown()).optional(),
  default_sales_partner: z.string().optional(),
  default_commission_rate: z.number().optional(),
  so_required: z.boolean().optional().default(false),
  dn_required: z.boolean().optional().default(false),
  disabled: z.boolean().optional().default(false),
  is_frozen: z.boolean().optional().default(false),
  portal_users: z.array(z.unknown()).optional(),
  lead_name: z.string().optional(),
  opportunity_name: z.string().optional(),
  prospect_name: z.string().optional(),
  market_segment: z.string().optional(),
  industry: z.string().optional(),
  website: z.string().optional(),
  language: z.string().optional(),
  customer_pos_id: z.string().optional(),
  customer_details: z.string().optional(),
  supplier_numbers: z.array(z.unknown()).optional(),
});

export type Customer = z.infer<typeof CustomerSchema>;

export const CustomerInsertSchema = CustomerSchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type CustomerInsert = z.infer<typeof CustomerInsertSchema>;
