import { z } from 'zod';

export const DeliveryNoteItemSchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  barcode: z.string().optional(),
  has_item_scanned: z.boolean().optional().default(false),
  item_code: z.string(),
  item_name: z.string(),
  customer_item_code: z.string().optional(),
  description: z.string().optional(),
  brand: z.string().optional(),
  item_group: z.string().optional(),
  image: z.string().optional(),
  image_view: z.string().optional(),
  qty: z.number(),
  stock_uom: z.string(),
  uom: z.string(),
  conversion_factor: z.number(),
  stock_qty: z.number().optional(),
  returned_qty: z.number().optional(),
  price_list_rate: z.number().optional(),
  base_price_list_rate: z.number().optional(),
  margin_type: z.enum(['Percentage', 'Amount']).optional(),
  margin_rate_or_amount: z.number().optional(),
  rate_with_margin: z.number().optional(),
  discount_percentage: z.number().optional(),
  discount_amount: z.number().optional(),
  distributed_discount_amount: z.number().optional(),
  base_rate_with_margin: z.number().optional(),
  rate: z.number().optional(),
  amount: z.number().optional(),
  base_rate: z.number().optional(),
  base_amount: z.number().optional(),
  pricing_rules: z.string().optional(),
  stock_uom_rate: z.number().optional(),
  is_free_item: z.boolean().optional().default(false),
  grant_commission: z.boolean().optional().default(false),
  net_rate: z.number().optional(),
  net_amount: z.number().optional(),
  item_tax_template: z.string().optional(),
  base_net_rate: z.number().optional(),
  base_net_amount: z.number().optional(),
  billed_amt: z.number().optional(),
  incoming_rate: z.number().optional(),
  weight_per_unit: z.number().optional(),
  total_weight: z.number().optional(),
  weight_uom: z.string().optional(),
  warehouse: z.string().optional(),
  target_warehouse: z.string().optional(),
  quality_inspection: z.string().optional(),
  allow_zero_valuation_rate: z.boolean().optional().default(false),
  against_sales_order: z.string().optional(),
  so_detail: z.string().optional(),
  against_sales_invoice: z.string().optional(),
  si_detail: z.string().optional(),
  dn_detail: z.string().optional(),
  against_pick_list: z.string().optional(),
  pick_list_item: z.string().optional(),
  serial_and_batch_bundle: z.string().optional(),
  use_serial_batch_fields: z.boolean().optional().default(false),
  serial_no: z.string().optional(),
  batch_no: z.string().optional(),
  actual_qty: z.number().optional(),
  actual_batch_qty: z.number().optional(),
  company_total_stock: z.number().optional(),
  installed_qty: z.number().optional(),
  packed_qty: z.number().optional().default(0),
  received_qty: z.number().optional(),
  expense_account: z.string().optional(),
  item_tax_rate: z.string().optional(),
  material_request: z.string().optional(),
  purchase_order: z.string().optional(),
  purchase_order_item: z.string().optional(),
  material_request_item: z.string().optional(),
  cost_center: z.string().optional().default(':Company'),
  project: z.string().optional(),
  page_break: z.boolean().optional().default(false),
});

export type DeliveryNoteItem = z.infer<typeof DeliveryNoteItemSchema>;

export const DeliveryNoteItemInsertSchema = DeliveryNoteItemSchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type DeliveryNoteItemInsert = z.infer<typeof DeliveryNoteItemInsertSchema>;
