import { z } from 'zod';

export const DeliveryNoteSchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  docstatus: z.number().default(0),
  naming_series: z.enum(['MAT-DN-.YYYY.-', 'MAT-DN-RET-.YYYY.-']),
  customer: z.string(),
  tax_id: z.string().optional(),
  customer_name: z.string().optional(),
  posting_date: z.string().default('Today'),
  posting_time: z.string().default('Now'),
  set_posting_time: z.boolean().optional().default(false),
  company: z.string(),
  amended_from: z.string().optional(),
  is_return: z.boolean().optional().default(false),
  issue_credit_note: z.boolean().optional().default(false),
  return_against: z.string().optional(),
  cost_center: z.string().optional(),
  project: z.string().optional(),
  currency: z.string(),
  conversion_rate: z.number(),
  selling_price_list: z.string(),
  price_list_currency: z.string(),
  plc_conversion_rate: z.number(),
  ignore_pricing_rule: z.boolean().optional().default(false),
  scan_barcode: z.string().optional(),
  last_scanned_warehouse: z.string().optional(),
  set_warehouse: z.string().optional(),
  set_target_warehouse: z.string().optional(),
  items: z.array(z.unknown()),
  total_qty: z.number().optional(),
  total_net_weight: z.number().optional(),
  base_total: z.number().optional(),
  base_net_total: z.number().optional(),
  total: z.number().optional(),
  net_total: z.number().optional(),
  tax_category: z.string().optional(),
  taxes_and_charges: z.string().optional(),
  shipping_rule: z.string().optional(),
  incoterm: z.string().optional(),
  named_place: z.string().optional(),
  taxes: z.array(z.unknown()).optional(),
  base_total_taxes_and_charges: z.number().optional(),
  total_taxes_and_charges: z.number().optional(),
  base_grand_total: z.number().optional(),
  base_rounding_adjustment: z.number().optional(),
  base_rounded_total: z.number().optional(),
  base_in_words: z.string().max(240).optional(),
  grand_total: z.number().optional(),
  rounding_adjustment: z.number().optional(),
  rounded_total: z.number().optional(),
  in_words: z.string().max(240).optional(),
  disable_rounded_total: z.boolean().optional().default(false),
  apply_discount_on: z.enum(['Grand Total', 'Net Total']).optional().default('Grand Total'),
  base_discount_amount: z.number().optional(),
  additional_discount_percentage: z.number().optional(),
  discount_amount: z.number().optional(),
  other_charges_calculation: z.string().optional(),
  item_wise_tax_details: z.array(z.unknown()).optional(),
  packed_items: z.array(z.unknown()).optional(),
  product_bundle_help: z.string().optional(),
  pricing_rules: z.array(z.unknown()).optional(),
  customer_address: z.string().optional(),
  address_display: z.string().optional(),
  contact_person: z.string().optional(),
  contact_display: z.string().optional(),
  contact_mobile: z.string().optional(),
  contact_email: z.string().email().optional(),
  shipping_address_name: z.string().optional(),
  shipping_address: z.string().optional(),
  dispatch_address_name: z.string().optional(),
  dispatch_address: z.string().optional(),
  company_address: z.string().optional(),
  company_address_display: z.string().optional(),
  company_contact_person: z.string().optional(),
  tc_name: z.string().optional(),
  terms: z.string().optional(),
  per_billed: z.number().optional(),
  status: z.enum(['Draft', 'To Bill', 'Partially Billed', 'Completed', 'Return', 'Return Issued', 'Cancelled', 'Closed']).default('Draft'),
  per_installed: z.number().optional(),
  installation_status: z.string().optional(),
  per_returned: z.number().optional(),
  transporter: z.string().optional(),
  lr_no: z.string().optional(),
  delivery_trip: z.string().optional(),
  driver: z.string().optional(),
  transporter_name: z.string().optional(),
  lr_date: z.string().optional().default('Today'),
  vehicle_no: z.string().optional(),
  driver_name: z.string().optional(),
  po_no: z.string().optional(),
  po_date: z.string().optional(),
  sales_partner: z.string().optional(),
  amount_eligible_for_commission: z.number().optional(),
  commission_rate: z.number().optional(),
  total_commission: z.number().optional(),
  sales_team: z.array(z.unknown()).optional(),
  auto_repeat: z.string().optional(),
  letter_head: z.string().optional(),
  print_without_amount: z.boolean().optional().default(false),
  group_same_items: z.boolean().optional().default(false),
  select_print_heading: z.string().optional(),
  language: z.string().optional(),
  is_internal_customer: z.boolean().optional().default(false),
  represents_company: z.string().optional(),
  inter_company_reference: z.string().optional(),
  customer_group: z.string().optional(),
  territory: z.string().optional(),
  utm_source: z.string().optional(),
  utm_campaign: z.string().optional(),
  utm_medium: z.string().optional(),
  utm_content: z.string().optional(),
  excise_page: z.string().optional(),
  instructions: z.string().optional(),
});

export type DeliveryNote = z.infer<typeof DeliveryNoteSchema>;

export const DeliveryNoteInsertSchema = DeliveryNoteSchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type DeliveryNoteInsert = z.infer<typeof DeliveryNoteInsertSchema>;
