import { z } from 'zod';

export const EmployeeSchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  employee: z.string().optional(),
  naming_series: z.enum(['HR-EMP-']).optional(),
  first_name: z.string(),
  middle_name: z.string().optional(),
  last_name: z.string().optional(),
  employee_name: z.string().optional(),
  gender: z.string(),
  date_of_birth: z.string(),
  salutation: z.string().optional(),
  date_of_joining: z.string(),
  image: z.string().optional(),
  status: z.enum(['Active', 'Inactive', 'Suspended', 'Left']).default('Active'),
  user_id: z.string().optional(),
  create_user_permission: z.boolean().optional().default(true),
  company: z.string(),
  department: z.string().optional(),
  employee_number: z.string().optional(),
  designation: z.string().optional(),
  reports_to: z.string().optional(),
  branch: z.string().optional(),
  scheduled_confirmation_date: z.string().optional(),
  final_confirmation_date: z.string().optional(),
  contract_end_date: z.string().optional(),
  notice_number_of_days: z.number().int().optional(),
  date_of_retirement: z.string().optional(),
  cell_number: z.string().optional(),
  personal_email: z.string().email().optional(),
  company_email: z.string().email().optional(),
  prefered_contact_email: z.enum(['Company Email', 'Personal Email', 'User ID']).optional(),
  prefered_email: z.string().email().optional(),
  unsubscribed: z.boolean().optional().default(false),
  current_address: z.string().optional(),
  current_accommodation_type: z.enum(['Rented', 'Owned']).optional(),
  permanent_address: z.string().optional(),
  permanent_accommodation_type: z.enum(['Rented', 'Owned']).optional(),
  person_to_be_contacted: z.string().optional(),
  emergency_phone_number: z.string().optional(),
  relation: z.string().optional(),
  attendance_device_id: z.string().optional(),
  holiday_list: z.string().optional(),
  ctc: z.number().optional(),
  salary_currency: z.string().optional(),
  salary_mode: z.enum(['Bank', 'Cash', 'Cheque']).optional(),
  bank_name: z.string().optional(),
  bank_ac_no: z.string().optional(),
  iban: z.string().optional(),
  marital_status: z.enum(['Single', 'Married', 'Divorced', 'Widowed']).optional(),
  family_background: z.string().optional(),
  blood_group: z.enum(['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-']).optional(),
  health_details: z.string().optional(),
  passport_number: z.string().optional(),
  valid_upto: z.string().optional(),
  date_of_issue: z.string().optional(),
  place_of_issue: z.string().optional(),
  bio: z.string().optional(),
  education: z.array(z.unknown()).optional(),
  external_work_history: z.array(z.unknown()).optional(),
  internal_work_history: z.array(z.unknown()).optional(),
  resignation_letter_date: z.string().optional(),
  relieving_date: z.string().optional(),
  held_on: z.string().optional(),
  new_workplace: z.string().optional(),
  leave_encashed: z.enum(['Yes', 'No']).optional(),
  encashment_date: z.string().optional(),
  reason_for_leaving: z.string().optional(),
  feedback: z.string().optional(),
  lft: z.number().int().optional(),
  rgt: z.number().int().optional(),
  old_parent: z.string().optional(),
});

export type Employee = z.infer<typeof EmployeeSchema>;

export const EmployeeInsertSchema = EmployeeSchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type EmployeeInsert = z.infer<typeof EmployeeInsertSchema>;
