import { z } from 'zod';

export const ItemSchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  naming_series: z.enum(['STO-ITEM-.YYYY.-']).optional(),
  item_code: z.string(),
  item_name: z.string().optional(),
  item_group: z.string(),
  stock_uom: z.string(),
  disabled: z.boolean().optional().default(false),
  allow_alternative_item: z.boolean().optional().default(false),
  is_stock_item: z.boolean().optional().default(true),
  has_variants: z.boolean().optional().default(false),
  is_fixed_asset: z.boolean().optional().default(false),
  auto_create_assets: z.boolean().optional().default(false),
  is_grouped_asset: z.boolean().optional().default(false),
  asset_category: z.string().optional(),
  asset_naming_series: z.string().optional(),
  opening_stock: z.number().optional(),
  standard_rate: z.number().optional(),
  over_delivery_receipt_allowance: z.number().optional(),
  over_billing_allowance: z.number().optional(),
  image: z.string().optional(),
  description: z.string().optional(),
  brand: z.string().optional(),
  uoms: z.array(z.unknown()).optional(),
  valuation_method: z.enum(['FIFO', 'Moving Average', 'LIFO']).optional(),
  valuation_rate: z.number().optional(),
  shelf_life_in_days: z.number().int().optional(),
  end_of_life: z.string().optional().default('2099-12-31'),
  default_material_request_type: z.enum(['Purchase', 'Material Transfer', 'Material Issue', 'Manufacture', 'Customer Provided']).optional().default('Purchase'),
  warranty_period: z.string().optional(),
  weight_per_unit: z.number().optional(),
  weight_uom: z.string().optional(),
  allow_negative_stock: z.boolean().optional().default(false),
  barcodes: z.array(z.unknown()).optional(),
  reorder_levels: z.array(z.unknown()).optional(),
  has_batch_no: z.boolean().optional().default(false),
  create_new_batch: z.boolean().optional().default(false),
  batch_number_series: z.string().optional(),
  has_expiry_date: z.boolean().optional().default(false),
  retain_sample: z.boolean().optional().default(false),
  sample_quantity: z.number().int().optional(),
  has_serial_no: z.boolean().optional().default(false),
  serial_no_series: z.string().optional(),
  item_defaults: z.array(z.unknown()).optional(),
  variant_of: z.string().optional(),
  variant_based_on: z.enum(['Item Attribute', 'Manufacturer']).optional().default('Item Attribute'),
  attributes: z.array(z.unknown()).optional(),
  enable_deferred_expense: z.boolean().optional().default(false),
  no_of_months_exp: z.number().int().optional(),
  enable_deferred_revenue: z.boolean().optional().default(false),
  no_of_months: z.number().int().optional(),
  purchase_uom: z.string().optional(),
  min_order_qty: z.number().optional().default(0),
  safety_stock: z.number().optional(),
  is_purchase_item: z.boolean().optional().default(true),
  lead_time_days: z.number().int().optional(),
  last_purchase_rate: z.number().optional(),
  is_customer_provided_item: z.boolean().optional().default(false),
  customer: z.string().optional(),
  delivered_by_supplier: z.boolean().optional().default(false),
  supplier_items: z.array(z.unknown()).optional(),
  country_of_origin: z.string().optional(),
  customs_tariff_number: z.string().optional(),
  sales_uom: z.string().optional(),
  grant_commission: z.boolean().optional().default(true),
  is_sales_item: z.boolean().optional().default(true),
  max_discount: z.number().optional(),
  customer_items: z.array(z.unknown()).optional(),
  taxes: z.array(z.unknown()).optional(),
  purchase_tax_withholding_category: z.string().optional(),
  sales_tax_withholding_category: z.string().optional(),
  inspection_required_before_purchase: z.boolean().optional().default(false),
  inspection_required_before_delivery: z.boolean().optional().default(false),
  quality_inspection_template: z.string().optional(),
  include_item_in_manufacturing: z.boolean().optional().default(true),
  is_sub_contracted_item: z.boolean().optional().default(false),
  default_bom: z.string().optional(),
  production_capacity: z.number().int().optional(),
  total_projected_qty: z.number().optional(),
  customer_code: z.string().optional(),
  default_manufacturer_part_no: z.string().optional(),
  default_item_manufacturer: z.string().optional(),
});

export type Item = z.infer<typeof ItemSchema>;

export const ItemInsertSchema = ItemSchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type ItemInsert = z.infer<typeof ItemInsertSchema>;
