import { z } from 'zod';

export const JobCardSchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  docstatus: z.number().default(0),
  naming_series: z.enum(['PO-JOB.#####']).default('PO-JOB.#####'),
  work_order: z.string(),
  employee: z.array(z.unknown()).optional(),
  is_subcontracted: z.boolean().optional().default(false),
  posting_date: z.string().optional().default('Today'),
  company: z.string(),
  project: z.string().optional(),
  bom_no: z.string().optional(),
  finished_good: z.string().optional(),
  production_item: z.string().optional(),
  semi_fg_bom: z.string().optional(),
  total_completed_qty: z.number().optional().default(0),
  for_quantity: z.number().optional(),
  transferred_qty: z.number().optional().default(0),
  manufactured_qty: z.number().optional(),
  process_loss_qty: z.number().optional(),
  operation: z.string(),
  source_warehouse: z.string().optional(),
  wip_warehouse: z.string().optional(),
  skip_material_transfer: z.boolean().optional().default(false),
  backflush_from_wip_warehouse: z.boolean().optional().default(false),
  workstation_type: z.string().optional(),
  workstation: z.string(),
  target_warehouse: z.string().optional(),
  items: z.array(z.unknown()).optional(),
  quality_inspection_template: z.string().optional(),
  quality_inspection: z.string().optional(),
  expected_start_date: z.string().optional(),
  time_required: z.number().optional(),
  expected_end_date: z.string().optional(),
  scheduled_time_logs: z.array(z.unknown()).optional(),
  actual_start_date: z.string().optional(),
  total_time_in_mins: z.number().optional(),
  actual_end_date: z.string().optional(),
  time_logs: z.array(z.unknown()).optional(),
  sub_operations: z.array(z.unknown()).optional(),
  scrap_items: z.array(z.unknown()).optional(),
  for_job_card: z.string().optional(),
  is_corrective_job_card: z.boolean().optional().default(false),
  hour_rate: z.number().optional(),
  for_operation: z.string().optional(),
  item_name: z.string().optional(),
  requested_qty: z.number().optional().default(0),
  status: z.enum(['Open', 'Work In Progress', 'Material Transferred', 'On Hold', 'Submitted', 'Cancelled', 'Completed']).optional().default('Open'),
  operation_row_id: z.number().int().optional(),
  is_paused: z.boolean().optional().default(false),
  track_semi_finished_goods: z.boolean().optional().default(false),
  operation_row_number: z.string().optional(),
  operation_id: z.string().optional(),
  sequence_id: z.number().int().optional(),
  remarks: z.string().optional(),
  serial_and_batch_bundle: z.string().optional(),
  batch_no: z.string().optional(),
  serial_no: z.string().optional(),
  barcode: z.string().optional(),
  started_time: z.string().optional(),
  current_time: z.number().int().optional(),
  amended_from: z.string().optional(),
});

export type JobCard = z.infer<typeof JobCardSchema>;

export const JobCardInsertSchema = JobCardSchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type JobCardInsert = z.infer<typeof JobCardInsertSchema>;
