import { z } from 'zod';

export const JournalEntrySchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  docstatus: z.number().default(0),
  company: z.string(),
  is_system_generated: z.boolean().optional().default(false),
  title: z.string().optional(),
  voucher_type: z.enum(['Journal Entry', 'Inter Company Journal Entry', 'Bank Entry', 'Cash Entry', 'Credit Card Entry', 'Debit Note', 'Credit Note', 'Contra Entry', 'Excise Entry', 'Write Off Entry', 'Opening Entry', 'Depreciation Entry', 'Asset Disposal', 'Periodic Accounting Entry', 'Exchange Rate Revaluation', 'Exchange Gain Or Loss', 'Deferred Revenue', 'Deferred Expense']).default('Journal Entry'),
  naming_series: z.enum(['ACC-JV-.YYYY.-']),
  process_deferred_accounting: z.string().optional(),
  reversal_of: z.string().optional(),
  from_template: z.string().optional(),
  posting_date: z.string(),
  finance_book: z.string().optional(),
  apply_tds: z.boolean().optional().default(false),
  tax_withholding_category: z.string().optional(),
  for_all_stock_asset_accounts: z.boolean().optional().default(true),
  stock_asset_account: z.string().optional(),
  periodic_entry_difference_account: z.string().optional(),
  accounts: z.array(z.unknown()),
  cheque_no: z.string().optional(),
  cheque_date: z.string().optional(),
  user_remark: z.string().optional(),
  total_debit: z.number().optional(),
  total_credit: z.number().optional(),
  difference: z.number().optional(),
  multi_currency: z.boolean().optional().default(false),
  total_amount_currency: z.string().optional(),
  total_amount: z.number().optional(),
  total_amount_in_words: z.string().optional(),
  tax_withholding_group: z.string().optional(),
  ignore_tax_withholding_threshold: z.boolean().optional().default(false),
  override_tax_withholding_entries: z.boolean().optional().default(false),
  tax_withholding_entries: z.array(z.unknown()).optional(),
  clearance_date: z.string().optional(),
  remark: z.string().optional(),
  inter_company_journal_entry_reference: z.string().optional(),
  bill_no: z.string().optional(),
  bill_date: z.string().optional(),
  due_date: z.string().optional(),
  write_off_based_on: z.enum(['Accounts Receivable', 'Accounts Payable']).optional().default('Accounts Receivable'),
  write_off_amount: z.number().optional(),
  pay_to_recd_from: z.string().optional(),
  letter_head: z.string().optional(),
  select_print_heading: z.string().optional(),
  mode_of_payment: z.string().optional(),
  payment_order: z.string().optional(),
  party_not_required: z.boolean().optional().default(false),
  is_opening: z.enum(['No', 'Yes']).optional().default('No'),
  stock_entry: z.string().optional(),
  auto_repeat: z.string().optional(),
  amended_from: z.string().optional(),
});

export type JournalEntry = z.infer<typeof JournalEntrySchema>;

export const JournalEntryInsertSchema = JournalEntrySchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type JournalEntryInsert = z.infer<typeof JournalEntryInsertSchema>;
