import { z } from 'zod';

export const MaterialRequestItemSchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  item_code: z.string(),
  item_name: z.string().optional(),
  schedule_date: z.string(),
  description: z.string().optional(),
  item_group: z.string().optional(),
  brand: z.string().optional(),
  image: z.string().optional(),
  qty: z.number(),
  stock_uom: z.string(),
  from_warehouse: z.string().optional(),
  warehouse: z.string().optional(),
  uom: z.string(),
  conversion_factor: z.number(),
  stock_qty: z.number().optional(),
  min_order_qty: z.number().optional(),
  projected_qty: z.number().optional(),
  picked_qty: z.number().optional(),
  actual_qty: z.number().optional(),
  ordered_qty: z.number().optional(),
  received_qty: z.number().optional(),
  rate: z.number().optional(),
  price_list_rate: z.number().optional(),
  amount: z.number().optional(),
  expense_account: z.string().optional(),
  wip_composite_asset: z.string().optional(),
  manufacturer: z.string().optional(),
  manufacturer_part_no: z.string().optional(),
  bom_no: z.string().optional(),
  project: z.string().optional(),
  cost_center: z.string().optional(),
  lead_time_date: z.string().optional(),
  sales_order: z.string().optional(),
  sales_order_item: z.string().optional(),
  packed_item: z.string().optional(),
  production_plan: z.string().optional(),
  material_request_plan_item: z.string().optional(),
  job_card_item: z.string().optional(),
  projected_on_hand: z.number().optional(),
  reorder_level: z.number().optional(),
  reorder_qty: z.number().optional(),
  page_break: z.boolean().optional().default(false),
});

export type MaterialRequestItem = z.infer<typeof MaterialRequestItemSchema>;

export const MaterialRequestItemInsertSchema = MaterialRequestItemSchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type MaterialRequestItemInsert = z.infer<typeof MaterialRequestItemInsertSchema>;
