import { z } from 'zod';

export const OpportunitySchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  naming_series: z.enum(['CRM-OPP-.YYYY.-']),
  opportunity_from: z.string(),
  party_name: z.string(),
  customer_name: z.string().optional(),
  status: z.enum(['Open', 'Quotation', 'Converted', 'Lost', 'Replied', 'Closed']).default('Open'),
  opportunity_type: z.string().optional(),
  opportunity_owner: z.string().optional(),
  sales_stage: z.string().optional().default('Prospecting'),
  expected_closing: z.string().optional(),
  probability: z.number().optional().default(100),
  no_of_employees: z.enum(['1-10', '11-50', '51-200', '201-500', '501-1000', '1000+']).optional(),
  annual_revenue: z.number().optional(),
  customer_group: z.string().optional(),
  industry: z.string().optional(),
  market_segment: z.string().optional(),
  website: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  country: z.string().optional(),
  territory: z.string().optional(),
  currency: z.string().optional(),
  conversion_rate: z.number().optional(),
  opportunity_amount: z.number().optional(),
  base_opportunity_amount: z.number().optional(),
  utm_source: z.string().optional(),
  utm_content: z.string().optional(),
  utm_campaign: z.string().optional(),
  utm_medium: z.string().optional(),
  company: z.string(),
  transaction_date: z.string().default('Today'),
  language: z.string().optional(),
  amended_from: z.string().optional(),
  title: z.string().optional(),
  first_response_time: z.number().optional(),
  lost_reasons: z.array(z.unknown()).optional(),
  order_lost_reason: z.string().optional(),
  competitors: z.array(z.unknown()).optional(),
  contact_person: z.string().optional(),
  job_title: z.string().optional(),
  contact_email: z.string().email().optional(),
  contact_mobile: z.string().optional(),
  whatsapp: z.string().optional(),
  phone: z.string().optional(),
  phone_ext: z.string().optional(),
  address_html: z.string().optional(),
  customer_address: z.string().optional(),
  address_display: z.string().optional(),
  contact_html: z.string().optional(),
  contact_display: z.string().optional(),
  items: z.array(z.unknown()).optional(),
  base_total: z.number().optional(),
  total: z.number().optional(),
  open_activities_html: z.string().optional(),
  all_activities_html: z.string().optional(),
  notes_html: z.string().optional(),
  notes: z.array(z.unknown()).optional(),
});

export type Opportunity = z.infer<typeof OpportunitySchema>;

export const OpportunityInsertSchema = OpportunitySchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type OpportunityInsert = z.infer<typeof OpportunityInsertSchema>;
