import { z } from 'zod';

export const PosProfileSchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  company: z.string(),
  customer: z.string().optional(),
  country: z.string().optional(),
  disabled: z.boolean().optional().default(false),
  warehouse: z.string(),
  company_address: z.string().optional(),
  payments: z.array(z.unknown()),
  set_grand_total_to_default_mop: z.boolean().optional().default(true),
  currency: z.string(),
  selling_price_list: z.string().optional(),
  write_off_account: z.string(),
  write_off_cost_center: z.string(),
  write_off_limit: z.number().default(1),
  income_account: z.string().optional(),
  expense_account: z.string().optional(),
  taxes_and_charges: z.string().optional(),
  tax_category: z.string().optional(),
  account_for_change_amount: z.string().optional(),
  disable_rounded_total: z.boolean().optional().default(false),
  apply_discount_on: z.enum(['Grand Total', 'Net Total']).optional().default('Grand Total'),
  allow_partial_payment: z.boolean().optional().default(false),
  cost_center: z.string().optional(),
  project: z.string().optional(),
  action_on_new_invoice: z.enum(['Always Ask', 'Save Changes and Load New Invoice', 'Discard Changes and Load New Invoice']).optional().default('Always Ask'),
  validate_stock_on_save: z.boolean().optional().default(false),
  update_stock: z.boolean().optional().default(true),
  ignore_pricing_rule: z.boolean().optional().default(false),
  print_receipt_on_order_complete: z.boolean().optional().default(false),
  hide_images: z.boolean().optional().default(false),
  hide_unavailable_items: z.boolean().optional().default(false),
  auto_add_item_to_cart: z.boolean().optional().default(false),
  allow_rate_change: z.boolean().optional().default(false),
  allow_discount_change: z.boolean().optional().default(false),
  allow_warehouse_change: z.boolean().optional().default(false),
  applicable_for_users: z.array(z.unknown()).optional(),
  item_groups: z.array(z.unknown()).optional(),
  customer_groups: z.array(z.unknown()).optional(),
  print_format: z.string().optional(),
  letter_head: z.string().optional(),
  tc_name: z.string().optional(),
  select_print_heading: z.string().optional(),
  utm_source: z.string().optional(),
  utm_campaign: z.string().optional(),
  utm_medium: z.string().optional(),
});

export type PosProfile = z.infer<typeof PosProfileSchema>;

export const PosProfileInsertSchema = PosProfileSchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type PosProfileInsert = z.infer<typeof PosProfileInsertSchema>;
