import { z } from 'zod';

export const PricingRuleSchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  naming_series: z.enum(['PRLE-.####']).optional().default('PRLE-.####'),
  title: z.string(),
  disable: z.boolean().optional().default(false),
  apply_on: z.enum(['Item Code', 'Item Group', 'Brand', 'Transaction']).default('Item Code'),
  price_or_product_discount: z.enum(['Price', 'Product']),
  warehouse: z.string().optional(),
  items: z.array(z.unknown()).optional(),
  item_groups: z.array(z.unknown()).optional(),
  brands: z.array(z.unknown()).optional(),
  mixed_conditions: z.boolean().optional().default(false),
  is_cumulative: z.boolean().optional().default(false),
  coupon_code_based: z.boolean().optional().default(false),
  apply_rule_on_other: z.enum(['Item Code', 'Item Group', 'Brand']).optional(),
  other_item_code: z.string().optional(),
  other_item_group: z.string().optional(),
  other_brand: z.string().optional(),
  selling: z.boolean().optional().default(false),
  buying: z.boolean().optional().default(false),
  applicable_for: z.enum(['Customer', 'Customer Group', 'Territory', 'Sales Partner', 'Campaign', 'Supplier', 'Supplier Group']).optional(),
  customer: z.string().optional(),
  customer_group: z.string().optional(),
  territory: z.string().optional(),
  sales_partner: z.string().optional(),
  campaign: z.string().optional(),
  supplier: z.string().optional(),
  supplier_group: z.string().optional(),
  min_qty: z.number().optional(),
  max_qty: z.number().optional(),
  min_amt: z.number().optional().default(0),
  max_amt: z.number().optional().default(0),
  same_item: z.boolean().optional().default(false),
  free_item: z.string().optional(),
  free_qty: z.number().optional().default(0),
  free_item_rate: z.number().optional(),
  free_item_uom: z.string().optional(),
  round_free_qty: z.boolean().optional().default(false),
  dont_enforce_free_item_qty: z.boolean().optional().default(false),
  is_recursive: z.boolean().optional().default(false),
  recurse_for: z.number().optional(),
  apply_recursion_over: z.number().optional().default(0),
  valid_from: z.string().optional().default('Today'),
  valid_upto: z.string().optional(),
  company: z.string().optional(),
  currency: z.string(),
  margin_type: z.enum(['Percentage', 'Amount']).optional().default('Percentage'),
  margin_rate_or_amount: z.number().optional().default(0),
  rate_or_discount: z.enum(['Rate', 'Discount Percentage', 'Discount Amount']).optional().default('Discount Percentage'),
  apply_discount_on: z.enum(['Grand Total', 'Net Total']).optional().default('Grand Total'),
  rate: z.number().optional().default(0),
  discount_amount: z.number().optional().default(0),
  discount_percentage: z.number().optional(),
  for_price_list: z.string().optional(),
  condition: z.string().optional(),
  apply_multiple_pricing_rules: z.boolean().optional().default(false),
  apply_discount_on_rate: z.boolean().optional().default(false),
  threshold_percentage: z.number().optional(),
  validate_applied_rule: z.boolean().optional().default(false),
  rule_description: z.string().optional(),
  has_priority: z.boolean().optional().default(false),
  priority: z.enum(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20']).optional(),
  pricing_rule_help: z.string().optional(),
  promotional_scheme_id: z.string().optional(),
  promotional_scheme: z.string().optional(),
});

export type PricingRule = z.infer<typeof PricingRuleSchema>;

export const PricingRuleInsertSchema = PricingRuleSchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type PricingRuleInsert = z.infer<typeof PricingRuleInsertSchema>;
