import { z } from 'zod';

export const ProductionPlanSchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  docstatus: z.number().default(0),
  naming_series: z.enum(['MFG-PP-.YYYY.-']),
  company: z.string(),
  get_items_from: z.enum(['Sales Order', 'Material Request']).optional(),
  posting_date: z.string().default('Today'),
  reserve_stock: z.boolean().optional().default(false),
  item_code: z.string().optional(),
  customer: z.string().optional(),
  warehouse: z.string().optional(),
  project: z.string().optional(),
  sales_order_status: z.enum(['To Deliver and Bill', 'To Bill', 'To Deliver']).optional(),
  from_date: z.string().optional(),
  to_date: z.string().optional(),
  from_delivery_date: z.string().optional(),
  to_delivery_date: z.string().optional(),
  combine_items: z.boolean().optional().default(false),
  sales_orders: z.array(z.unknown()).optional(),
  material_requests: z.array(z.unknown()).optional(),
  po_items: z.array(z.unknown()),
  prod_plan_references: z.array(z.unknown()).optional(),
  sub_assembly_warehouse: z.string().optional(),
  skip_available_sub_assembly_item: z.boolean().optional().default(true),
  combine_sub_items: z.boolean().optional().default(false),
  sub_assembly_items: z.array(z.unknown()).optional(),
  include_non_stock_items: z.boolean().optional().default(true),
  include_subcontracted_items: z.boolean().optional().default(true),
  consider_minimum_order_qty: z.boolean().optional().default(false),
  include_safety_stock: z.boolean().optional().default(false),
  ignore_existing_ordered_qty: z.boolean().optional().default(true),
  for_warehouse: z.string().optional(),
  mr_items: z.array(z.unknown()).optional(),
  total_planned_qty: z.number().optional().default(0),
  total_produced_qty: z.number().optional().default(0),
  status: z.enum(['Draft', 'Submitted', 'Not Started', 'In Process', 'Completed', 'Closed', 'Cancelled', 'Material Requested']).optional().default('Draft'),
  warehouses: z.array(z.unknown()).optional(),
  amended_from: z.string().optional(),
});

export type ProductionPlan = z.infer<typeof ProductionPlanSchema>;

export const ProductionPlanInsertSchema = ProductionPlanSchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type ProductionPlanInsert = z.infer<typeof ProductionPlanInsertSchema>;
