import { z } from 'zod';

export const ProjectSchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  naming_series: z.enum(['PROJ-.####']),
  project_name: z.string(),
  status: z.enum(['Open', 'Completed', 'Cancelled']).optional().default('Open'),
  project_type: z.string().optional(),
  is_active: z.enum(['Yes', 'No']).optional(),
  percent_complete_method: z.enum(['Manual', 'Task Completion', 'Task Progress', 'Task Weight']).optional().default('Task Completion'),
  percent_complete: z.number().optional(),
  project_template: z.string().optional(),
  expected_start_date: z.string().optional(),
  expected_end_date: z.string().optional(),
  priority: z.enum(['Medium', 'Low', 'High']).optional(),
  department: z.string().optional(),
  customer: z.string().optional(),
  sales_order: z.string().optional(),
  users: z.array(z.unknown()).optional(),
  copied_from: z.string().optional(),
  notes: z.string().optional(),
  actual_start_date: z.string().optional(),
  actual_time: z.number().optional(),
  actual_end_date: z.string().optional(),
  estimated_costing: z.number().optional(),
  total_costing_amount: z.number().optional(),
  total_purchase_cost: z.number().optional(),
  company: z.string(),
  total_sales_amount: z.number().optional(),
  total_billable_amount: z.number().optional(),
  total_billed_amount: z.number().optional(),
  total_consumed_material_cost: z.number().optional(),
  cost_center: z.string().optional(),
  gross_margin: z.number().optional(),
  per_gross_margin: z.number().optional(),
  collect_progress: z.boolean().optional().default(false),
  holiday_list: z.string().optional(),
  frequency: z.enum(['Hourly', 'Twice Daily', 'Daily', 'Weekly']).optional(),
  from_time: z.string().optional(),
  to_time: z.string().optional(),
  first_email: z.string().optional(),
  second_email: z.string().optional(),
  daily_time_to_send: z.string().optional(),
  day_to_send: z.enum(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']).optional(),
  weekly_time_to_send: z.string().optional(),
  subject: z.string().optional(),
  message: z.string().optional(),
});

export type Project = z.infer<typeof ProjectSchema>;

export const ProjectInsertSchema = ProjectSchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type ProjectInsert = z.infer<typeof ProjectInsertSchema>;
