import { z } from 'zod';

export const QuotationItemSchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  item_code: z.string().optional(),
  item_name: z.string(),
  customer_item_code: z.string().optional(),
  is_free_item: z.boolean().optional().default(false),
  is_alternative: z.boolean().optional().default(false),
  has_alternative_item: z.boolean().optional().default(false),
  description: z.string().optional(),
  item_group: z.string().optional(),
  brand: z.string().optional(),
  image: z.string().optional(),
  image_view: z.string().optional(),
  qty: z.number(),
  stock_uom: z.string().optional(),
  uom: z.string(),
  conversion_factor: z.number(),
  stock_qty: z.number().optional(),
  ordered_qty: z.number().default(0),
  actual_qty: z.number().optional(),
  company_total_stock: z.number().optional(),
  price_list_rate: z.number().optional(),
  base_price_list_rate: z.number().optional(),
  margin_type: z.enum(['Percentage', 'Amount']).optional(),
  margin_rate_or_amount: z.number().optional(),
  rate_with_margin: z.number().optional(),
  discount_percentage: z.number().optional(),
  discount_amount: z.number().optional(),
  distributed_discount_amount: z.number().optional(),
  base_rate_with_margin: z.number().optional(),
  rate: z.number().optional(),
  net_rate: z.number().optional(),
  amount: z.number().optional(),
  net_amount: z.number().optional(),
  item_tax_template: z.string().optional(),
  base_rate: z.number().optional(),
  base_net_rate: z.number().optional(),
  base_amount: z.number().optional(),
  base_net_amount: z.number().optional(),
  pricing_rules: z.string().optional(),
  stock_uom_rate: z.number().optional(),
  valuation_rate: z.number().optional(),
  gross_profit: z.number().optional(),
  weight_per_unit: z.number().optional(),
  total_weight: z.number().optional(),
  weight_uom: z.string().optional(),
  warehouse: z.string().optional(),
  against_blanket_order: z.boolean().optional().default(false),
  blanket_order: z.string().optional(),
  blanket_order_rate: z.number().optional(),
  prevdoc_doctype: z.string().optional(),
  prevdoc_docname: z.string().optional(),
  projected_qty: z.number().optional(),
  item_tax_rate: z.string().optional(),
  additional_notes: z.string().optional(),
  page_break: z.boolean().optional().default(false),
});

export type QuotationItem = z.infer<typeof QuotationItemSchema>;

export const QuotationItemInsertSchema = QuotationItemSchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type QuotationItemInsert = z.infer<typeof QuotationItemInsertSchema>;
