import { z } from 'zod';

export const SalesInvoiceItemSchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  barcode: z.string().optional(),
  has_item_scanned: z.boolean().optional().default(false),
  item_code: z.string().optional(),
  item_name: z.string(),
  customer_item_code: z.string().optional(),
  description: z.string().optional(),
  item_group: z.string().optional(),
  brand: z.string().optional(),
  image: z.string().optional(),
  image_view: z.string().optional(),
  qty: z.number().optional(),
  stock_uom: z.string().optional(),
  uom: z.string(),
  conversion_factor: z.number(),
  stock_qty: z.number().optional(),
  price_list_rate: z.number().optional(),
  base_price_list_rate: z.number().optional(),
  margin_type: z.enum(['Percentage', 'Amount']).optional(),
  margin_rate_or_amount: z.number().optional(),
  rate_with_margin: z.number().optional(),
  discount_percentage: z.number().optional(),
  discount_amount: z.number().optional(),
  distributed_discount_amount: z.number().optional(),
  base_rate_with_margin: z.number().optional(),
  rate: z.number(),
  amount: z.number(),
  item_tax_template: z.string().optional(),
  tax_withholding_category: z.string().optional(),
  base_rate: z.number(),
  base_amount: z.number(),
  pricing_rules: z.string().optional(),
  stock_uom_rate: z.number().optional(),
  is_free_item: z.boolean().optional().default(false),
  apply_tds: z.boolean().optional().default(true),
  grant_commission: z.boolean().optional().default(false),
  net_rate: z.number().optional(),
  net_amount: z.number().optional(),
  base_net_rate: z.number().optional(),
  base_net_amount: z.number().optional(),
  delivered_by_supplier: z.boolean().optional().default(false),
  income_account: z.string(),
  is_fixed_asset: z.boolean().optional().default(false),
  asset: z.string().optional(),
  finance_book: z.string().optional(),
  expense_account: z.string().optional(),
  discount_account: z.string().optional(),
  deferred_revenue_account: z.string().optional(),
  service_stop_date: z.string().optional(),
  enable_deferred_revenue: z.boolean().optional().default(false),
  service_start_date: z.string().optional(),
  service_end_date: z.string().optional(),
  weight_per_unit: z.number().optional(),
  total_weight: z.number().optional(),
  weight_uom: z.string().optional(),
  warehouse: z.string().optional(),
  target_warehouse: z.string().optional(),
  quality_inspection: z.string().optional(),
  serial_and_batch_bundle: z.string().optional(),
  use_serial_batch_fields: z.boolean().optional().default(false),
  allow_zero_valuation_rate: z.boolean().optional().default(false),
  incoming_rate: z.number().optional(),
  item_tax_rate: z.string().optional(),
  actual_batch_qty: z.number().optional(),
  serial_no: z.string().optional(),
  batch_no: z.string().optional(),
  actual_qty: z.number().optional(),
  company_total_stock: z.number().optional(),
  sales_order: z.string().optional(),
  so_detail: z.string().optional(),
  sales_invoice_item: z.string().optional(),
  delivery_note: z.string().optional(),
  dn_detail: z.string().optional(),
  delivered_qty: z.number().optional(),
  pos_invoice: z.string().optional(),
  pos_invoice_item: z.string().optional(),
  scio_detail: z.string().optional(),
  purchase_order: z.string().optional(),
  purchase_order_item: z.string().optional(),
  cost_center: z.string().default(':Company'),
  project: z.string().optional(),
  page_break: z.boolean().optional().default(false),
});

export type SalesInvoiceItem = z.infer<typeof SalesInvoiceItemSchema>;

export const SalesInvoiceItemInsertSchema = SalesInvoiceItemSchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type SalesInvoiceItemInsert = z.infer<typeof SalesInvoiceItemInsertSchema>;
