import { z } from 'zod';

export const SalesOrderSchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  docstatus: z.number().default(0),
  company: z.string(),
  naming_series: z.enum(['SAL-ORD-.YYYY.-']),
  customer: z.string(),
  customer_name: z.string().optional(),
  order_type: z.enum(['Sales', 'Maintenance', 'Shopping Cart']).default('Sales'),
  transaction_date: z.string().default('Today'),
  delivery_date: z.string().optional(),
  tax_id: z.string().optional(),
  skip_delivery_note: z.boolean().optional().default(false),
  has_unit_price_items: z.boolean().optional().default(false),
  is_subcontracted: z.boolean().optional().default(false),
  amended_from: z.string().optional(),
  cost_center: z.string().optional(),
  project: z.string().optional(),
  currency: z.string(),
  conversion_rate: z.number(),
  selling_price_list: z.string(),
  price_list_currency: z.string(),
  plc_conversion_rate: z.number(),
  ignore_pricing_rule: z.boolean().optional().default(false),
  scan_barcode: z.string().optional(),
  last_scanned_warehouse: z.string().optional(),
  set_warehouse: z.string().optional(),
  reserve_stock: z.boolean().optional().default(false),
  items: z.array(z.unknown()),
  total_qty: z.number().optional(),
  total_net_weight: z.number().optional(),
  base_total: z.number().optional(),
  base_net_total: z.number().optional(),
  total: z.number().optional(),
  net_total: z.number().optional(),
  tax_category: z.string().optional(),
  taxes_and_charges: z.string().optional(),
  shipping_rule: z.string().optional(),
  incoterm: z.string().optional(),
  named_place: z.string().optional(),
  taxes: z.array(z.unknown()).optional(),
  base_total_taxes_and_charges: z.number().optional(),
  total_taxes_and_charges: z.number().optional(),
  grand_total: z.number().optional(),
  in_words: z.string().max(240).optional(),
  disable_rounded_total: z.boolean().optional().default(false),
  rounded_total: z.number().optional(),
  rounding_adjustment: z.number().optional(),
  base_grand_total: z.number().optional(),
  base_in_words: z.string().max(240).optional(),
  base_rounded_total: z.number().optional(),
  base_rounding_adjustment: z.number().optional(),
  advance_paid: z.number().optional(),
  apply_discount_on: z.enum(['Grand Total', 'Net Total']).optional().default('Grand Total'),
  base_discount_amount: z.number().optional(),
  coupon_code: z.string().optional(),
  additional_discount_percentage: z.number().optional(),
  discount_amount: z.number().optional(),
  other_charges_calculation: z.string().optional(),
  item_wise_tax_details: z.array(z.unknown()).optional(),
  packed_items: z.array(z.unknown()).optional(),
  pricing_rules: z.array(z.unknown()).optional(),
  customer_address: z.string().optional(),
  address_display: z.string().optional(),
  customer_group: z.string().optional(),
  territory: z.string().optional(),
  contact_person: z.string().optional(),
  contact_display: z.string().optional(),
  contact_phone: z.string().optional(),
  contact_mobile: z.string().optional(),
  contact_email: z.string().email().optional(),
  shipping_address_name: z.string().optional(),
  shipping_address: z.string().optional(),
  dispatch_address_name: z.string().optional(),
  dispatch_address: z.string().optional(),
  company_address: z.string().optional(),
  company_address_display: z.string().optional(),
  company_contact_person: z.string().optional(),
  payment_terms_template: z.string().optional(),
  payment_schedule: z.array(z.unknown()).optional(),
  tc_name: z.string().optional(),
  terms: z.string().optional(),
  status: z.enum(['Draft', 'On Hold', 'To Pay', 'To Deliver and Bill', 'To Bill', 'To Deliver', 'Completed', 'Cancelled', 'Closed']).default('Draft'),
  delivery_status: z.enum(['Not Delivered', 'Fully Delivered', 'Partly Delivered', 'Closed', 'Not Applicable']).optional(),
  per_delivered: z.number().optional(),
  per_billed: z.number().optional(),
  per_picked: z.number().optional(),
  billing_status: z.enum(['Not Billed', 'Fully Billed', 'Partly Billed', 'Closed']).optional(),
  advance_payment_status: z.enum(['Not Requested', 'Requested', 'Partially Paid', 'Fully Paid']).optional(),
  sales_partner: z.string().optional(),
  amount_eligible_for_commission: z.number().optional(),
  commission_rate: z.number().optional(),
  total_commission: z.number().optional(),
  sales_team: z.array(z.unknown()).optional(),
  loyalty_points: z.number().int().optional(),
  loyalty_amount: z.number().optional(),
  from_date: z.string().optional(),
  to_date: z.string().optional(),
  auto_repeat: z.string().optional(),
  letter_head: z.string().optional(),
  group_same_items: z.boolean().optional().default(false),
  select_print_heading: z.string().optional(),
  language: z.string().optional(),
  is_internal_customer: z.boolean().optional().default(false),
  po_no: z.string().optional(),
  po_date: z.string().optional(),
  represents_company: z.string().optional(),
  utm_source: z.string().optional(),
  utm_campaign: z.string().optional(),
  utm_medium: z.string().optional(),
  utm_content: z.string().optional(),
  inter_company_order_reference: z.string().optional(),
  party_account_currency: z.string().optional(),
});

export type SalesOrder = z.infer<typeof SalesOrderSchema>;

export const SalesOrderInsertSchema = SalesOrderSchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type SalesOrderInsert = z.infer<typeof SalesOrderInsertSchema>;
