import { z } from 'zod';

export const ShipmentSchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  docstatus: z.number().default(0),
  pickup_from_type: z.enum(['Company', 'Customer', 'Supplier']).optional().default('Company'),
  pickup_company: z.string().optional(),
  pickup_customer: z.string().optional(),
  pickup_supplier: z.string().optional(),
  pickup: z.string().optional(),
  pickup_address_name: z.string(),
  pickup_address: z.string().optional(),
  pickup_contact_person: z.string().optional(),
  pickup_contact_name: z.string().optional(),
  pickup_contact_email: z.string().optional(),
  pickup_contact: z.string().optional(),
  delivery_to_type: z.enum(['Company', 'Customer', 'Supplier']).optional().default('Customer'),
  delivery_company: z.string().optional(),
  delivery_customer: z.string().optional(),
  delivery_supplier: z.string().optional(),
  delivery_to: z.string().optional(),
  delivery_address_name: z.string(),
  delivery_address: z.string().optional(),
  delivery_contact_name: z.string().optional(),
  delivery_contact_email: z.string().optional(),
  delivery_contact: z.string().optional(),
  shipment_parcel: z.array(z.unknown()).optional(),
  parcel_template: z.string().optional(),
  total_weight: z.number().optional(),
  shipment_delivery_note: z.array(z.unknown()).optional(),
  pallets: z.enum(['No', 'Yes']).optional().default('No'),
  value_of_goods: z.number(),
  pickup_date: z.string(),
  pickup_from: z.string().default('09:00'),
  pickup_to: z.string().default('17:00'),
  shipment_type: z.enum(['Goods', 'Documents']).optional().default('Goods'),
  pickup_type: z.enum(['Pickup', 'Self delivery']).optional().default('Pickup'),
  incoterm: z.string().optional(),
  description_of_content: z.string(),
  service_provider: z.string().optional(),
  shipment_id: z.string().optional(),
  shipment_amount: z.number().optional(),
  status: z.enum(['Draft', 'Submitted', 'Booked', 'Cancelled', 'Completed']).optional(),
  tracking_url: z.string().optional(),
  carrier: z.string().optional(),
  carrier_service: z.string().optional(),
  awb_number: z.string().optional(),
  tracking_status: z.enum(['In Progress', 'Delivered', 'Returned', 'Lost']).optional(),
  tracking_status_info: z.string().optional(),
  amended_from: z.string().optional(),
});

export type Shipment = z.infer<typeof ShipmentSchema>;

export const ShipmentInsertSchema = ShipmentSchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type ShipmentInsert = z.infer<typeof ShipmentInsertSchema>;
