import { z } from 'zod';

export const StockEntrySchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  docstatus: z.number().default(0),
  naming_series: z.enum(['MAT-STE-.YYYY.-']),
  stock_entry_type: z.string(),
  outgoing_stock_entry: z.string().optional(),
  purpose: z.enum(['Material Issue', 'Material Receipt', 'Material Transfer', 'Material Transfer for Manufacture', 'Material Consumption for Manufacture', 'Manufacture', 'Repack', 'Send to Subcontractor', 'Disassemble', 'Receive from Customer', 'Return Raw Material to Customer', 'Subcontracting Delivery', 'Subcontracting Return']).optional(),
  add_to_transit: z.boolean().optional().default(false),
  work_order: z.string().optional(),
  job_card: z.string().optional(),
  purchase_order: z.string().optional(),
  subcontracting_order: z.string().optional(),
  subcontracting_inward_order: z.string().optional(),
  delivery_note_no: z.string().optional(),
  sales_invoice_no: z.string().optional(),
  pick_list: z.string().optional(),
  purchase_receipt_no: z.string().optional(),
  asset_repair: z.string().optional(),
  company: z.string(),
  posting_date: z.string().optional().default('Today'),
  posting_time: z.string().optional().default('Now'),
  set_posting_time: z.boolean().optional().default(false),
  inspection_required: z.boolean().optional().default(false),
  apply_putaway_rule: z.boolean().optional().default(false),
  is_additional_transfer_entry: z.boolean().optional().default(false),
  from_bom: z.boolean().optional().default(false),
  use_multi_level_bom: z.boolean().optional().default(true),
  bom_no: z.string().optional(),
  fg_completed_qty: z.number().optional(),
  process_loss_percentage: z.number().optional(),
  process_loss_qty: z.number().optional(),
  from_warehouse: z.string().optional(),
  source_warehouse_address: z.string().optional(),
  source_address_display: z.string().optional(),
  to_warehouse: z.string().optional(),
  target_warehouse_address: z.string().optional(),
  target_address_display: z.string().optional(),
  scan_barcode: z.string().optional(),
  last_scanned_warehouse: z.string().optional(),
  items: z.array(z.unknown()),
  total_outgoing_value: z.number().optional(),
  total_incoming_value: z.number().optional(),
  value_difference: z.number().optional(),
  additional_costs: z.array(z.unknown()).optional(),
  total_additional_costs: z.number().optional(),
  supplier: z.string().optional(),
  supplier_name: z.string().optional(),
  supplier_address: z.string().optional(),
  address_display: z.string().optional(),
  project: z.string().optional(),
  select_print_heading: z.string().optional(),
  letter_head: z.string().optional(),
  is_opening: z.enum(['No', 'Yes']).optional(),
  remarks: z.string().optional(),
  per_transferred: z.number().optional(),
  total_amount: z.number().optional(),
  amended_from: z.string().optional(),
  credit_note: z.string().optional(),
  is_return: z.boolean().optional().default(false),
});

export type StockEntry = z.infer<typeof StockEntrySchema>;

export const StockEntryInsertSchema = StockEntrySchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type StockEntryInsert = z.infer<typeof StockEntryInsertSchema>;
