import { z } from 'zod';

export const StockSettingsSchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  item_naming_by: z.enum(['Item Code', 'Naming Series']).optional().default('Item Code'),
  valuation_method: z.enum(['FIFO', 'Moving Average', 'LIFO']).optional(),
  item_group: z.string().optional(),
  default_warehouse: z.string().optional(),
  sample_retention_warehouse: z.string().optional(),
  stock_uom: z.string().optional(),
  auto_insert_price_list_rate_if_missing: z.boolean().optional().default(false),
  update_price_list_based_on: z.enum(['Rate', 'Price List Rate']).optional().default('Rate'),
  update_existing_price_list_rate: z.boolean().optional().default(false),
  allow_to_edit_stock_uom_qty_for_sales: z.boolean().optional().default(false),
  allow_to_edit_stock_uom_qty_for_purchase: z.boolean().optional().default(false),
  allow_uom_with_conversion_rate_defined_in_item: z.boolean().optional().default(false),
  over_delivery_receipt_allowance: z.number().optional(),
  mr_qty_allowance: z.number().optional(),
  over_picking_allowance: z.number().optional(),
  role_allowed_to_over_deliver_receive: z.string().optional(),
  allow_negative_stock: z.boolean().optional().default(false),
  show_barcode_field: z.boolean().optional().default(true),
  clean_description_html: z.boolean().optional().default(true),
  allow_internal_transfer_at_arms_length_price: z.boolean().optional().default(false),
  validate_material_transfer_warehouses: z.boolean().optional().default(false),
  allow_existing_serial_no: z.boolean().optional().default(true),
  do_not_use_batchwise_valuation: z.boolean().optional().default(false),
  auto_create_serial_and_batch_bundle_for_outward: z.boolean().optional().default(true),
  pick_serial_and_batch_based_on: z.enum(['FIFO', 'LIFO', 'Expiry']).optional().default('FIFO'),
  disable_serial_no_and_batch_selector: z.boolean().optional().default(false),
  use_serial_batch_fields: z.boolean().optional().default(true),
  do_not_update_serial_batch_on_creation_of_auto_bundle: z.boolean().optional().default(true),
  set_serial_and_batch_bundle_naming_based_on_naming_series: z.boolean().optional().default(false),
  use_naming_series: z.boolean().optional().default(false),
  naming_series_prefix: z.string().optional().default('BATCH-'),
  enable_stock_reservation: z.boolean().optional().default(false),
  auto_reserve_stock: z.boolean().optional().default(false),
  allow_partial_reservation: z.boolean().optional().default(true),
  auto_reserve_stock_for_sales_order_on_purchase: z.boolean().optional().default(false),
  auto_reserve_serial_and_batch: z.boolean().optional().default(true),
  action_if_quality_inspection_is_not_submitted: z.enum(['Stop', 'Warn']).optional().default('Stop'),
  action_if_quality_inspection_is_rejected: z.enum(['Stop', 'Warn']).optional().default('Stop'),
  allow_to_make_quality_inspection_after_purchase_or_delivery: z.boolean().optional().default(false),
  auto_indent: z.boolean().optional().default(false),
  reorder_email_notify: z.boolean().optional().default(false),
  allow_from_dn: z.boolean().optional().default(false),
  allow_from_pr: z.boolean().optional().default(false),
  stock_frozen_upto: z.string().optional(),
  stock_frozen_upto_days: z.number().int().optional(),
  role_allowed_to_create_edit_back_dated_transactions: z.string().optional(),
  stock_auth_role: z.string().optional(),
});

export type StockSettings = z.infer<typeof StockSettingsSchema>;

export const StockSettingsInsertSchema = StockSettingsSchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type StockSettingsInsert = z.infer<typeof StockSettingsInsertSchema>;
