import { z } from 'zod';

export const SubcontractingReceiptItemSchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  item_code: z.string(),
  item_name: z.string().optional(),
  is_scrap_item: z.boolean().optional().default(false),
  description: z.string().optional(),
  brand: z.string().optional(),
  image: z.string().optional(),
  image_view: z.string().optional(),
  received_qty: z.number().default(0),
  qty: z.number().optional(),
  rejected_qty: z.number().optional(),
  returned_qty: z.number().optional().default(0),
  stock_uom: z.string(),
  conversion_factor: z.number().optional().default(1),
  rate: z.number().optional(),
  amount: z.number().optional(),
  landed_cost_voucher_amount: z.number().optional(),
  rm_cost_per_qty: z.number().optional().default(0),
  service_cost_per_qty: z.number().default(0),
  additional_cost_per_qty: z.number().optional().default(0),
  scrap_cost_per_qty: z.number().optional().default(0),
  rm_supp_cost: z.number().optional(),
  warehouse: z.string().optional(),
  subcontracting_order: z.string().optional(),
  subcontracting_order_item: z.string().optional(),
  subcontracting_receipt_item: z.string().optional(),
  job_card: z.string().optional(),
  rejected_warehouse: z.string().optional(),
  bom: z.string().optional(),
  include_exploded_items: z.boolean().optional().default(false),
  quality_inspection: z.string().optional(),
  schedule_date: z.string().optional(),
  reference_name: z.string().optional(),
  serial_and_batch_bundle: z.string().optional(),
  use_serial_batch_fields: z.boolean().optional().default(false),
  rejected_serial_and_batch_bundle: z.string().optional(),
  serial_no: z.string().optional(),
  rejected_serial_no: z.string().optional(),
  batch_no: z.string().optional(),
  manufacturer: z.string().optional(),
  manufacturer_part_no: z.string().optional(),
  expense_account: z.string().optional(),
  service_expense_account: z.string().optional(),
  cost_center: z.string().optional().default(':Company'),
  project: z.string().optional(),
  page_break: z.boolean().optional().default(false),
  purchase_order: z.string().optional(),
  purchase_order_item: z.string().optional(),
});

export type SubcontractingReceiptItem = z.infer<typeof SubcontractingReceiptItemSchema>;

export const SubcontractingReceiptItemInsertSchema = SubcontractingReceiptItemSchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type SubcontractingReceiptItemInsert = z.infer<typeof SubcontractingReceiptItemInsertSchema>;
