import { z } from 'zod';

export const SupplierSchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  naming_series: z.enum(['SUP-.YYYY.-']).optional(),
  supplier_name: z.string(),
  supplier_type: z.enum(['Company', 'Individual', 'Partnership']).default('Company'),
  gender: z.string().optional(),
  supplier_group: z.string().optional(),
  country: z.string().optional(),
  is_transporter: z.boolean().optional().default(false),
  image: z.string().optional(),
  default_currency: z.string().optional(),
  default_bank_account: z.string().optional(),
  default_price_list: z.string().optional(),
  is_internal_supplier: z.boolean().optional().default(false),
  represents_company: z.string().optional(),
  companies: z.array(z.unknown()).optional(),
  supplier_details: z.string().optional(),
  website: z.string().optional(),
  language: z.string().optional(),
  customer_numbers: z.array(z.unknown()).optional(),
  tax_id: z.string().optional(),
  tax_category: z.string().optional(),
  tax_withholding_category: z.string().optional(),
  tax_withholding_group: z.string().optional(),
  address_html: z.string().optional(),
  contact_html: z.string().optional(),
  supplier_primary_address: z.string().optional(),
  primary_address: z.string().optional(),
  supplier_primary_contact: z.string().optional(),
  mobile_no: z.string().optional(),
  email_id: z.string().optional(),
  payment_terms: z.string().optional(),
  accounts: z.array(z.unknown()).optional(),
  allow_purchase_invoice_creation_without_purchase_order: z.boolean().optional().default(false),
  allow_purchase_invoice_creation_without_purchase_receipt: z.boolean().optional().default(false),
  disabled: z.boolean().optional().default(false),
  is_frozen: z.boolean().optional().default(false),
  warn_rfqs: z.boolean().optional().default(false),
  warn_pos: z.boolean().optional().default(false),
  prevent_rfqs: z.boolean().optional().default(false),
  prevent_pos: z.boolean().optional().default(false),
  on_hold: z.boolean().optional().default(false),
  hold_type: z.enum(['All', 'Invoices', 'Payments']).optional(),
  release_date: z.string().optional(),
  portal_users: z.array(z.unknown()).optional(),
});

export type Supplier = z.infer<typeof SupplierSchema>;

export const SupplierInsertSchema = SupplierSchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type SupplierInsert = z.infer<typeof SupplierInsertSchema>;
