import { z } from 'zod';

export const SupplierQuotationItemSchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  item_code: z.string(),
  supplier_part_no: z.string().optional(),
  item_name: z.string().optional(),
  lead_time_days: z.number().int().optional(),
  expected_delivery_date: z.string().optional(),
  is_free_item: z.boolean().optional().default(false),
  description: z.string().optional(),
  item_group: z.string().optional(),
  brand: z.string().optional(),
  image: z.string().optional(),
  image_view: z.string().optional(),
  qty: z.number(),
  stock_uom: z.string(),
  uom: z.string(),
  conversion_factor: z.number(),
  stock_qty: z.number().optional(),
  price_list_rate: z.number().optional(),
  base_price_list_rate: z.number().optional(),
  margin_type: z.enum(['Percentage', 'Amount']).optional(),
  margin_rate_or_amount: z.number().optional(),
  rate_with_margin: z.number().optional(),
  discount_percentage: z.number().optional(),
  discount_amount: z.number().optional(),
  distributed_discount_amount: z.number().optional(),
  rate: z.number().optional(),
  amount: z.number().optional(),
  item_tax_template: z.string().optional(),
  base_rate: z.number(),
  base_amount: z.number(),
  pricing_rules: z.string().optional(),
  net_rate: z.number().optional(),
  net_amount: z.number().optional(),
  base_net_rate: z.number().optional(),
  base_net_amount: z.number().optional(),
  weight_per_unit: z.number().optional(),
  total_weight: z.number().optional(),
  weight_uom: z.string().optional(),
  warehouse: z.string().optional(),
  prevdoc_doctype: z.string().optional(),
  material_request: z.string().optional(),
  sales_order: z.string().optional(),
  request_for_quotation: z.string().optional(),
  material_request_item: z.string().optional(),
  request_for_quotation_item: z.string().optional(),
  item_tax_rate: z.string().optional(),
  manufacturer: z.string().optional(),
  manufacturer_part_no: z.string().optional(),
  cost_center: z.string().optional(),
  project: z.string().optional(),
  page_break: z.boolean().optional().default(false),
});

export type SupplierQuotationItem = z.infer<typeof SupplierQuotationItemSchema>;

export const SupplierQuotationItemInsertSchema = SupplierQuotationItemSchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type SupplierQuotationItemInsert = z.infer<typeof SupplierQuotationItemInsertSchema>;
