import { z } from 'zod';

export const TaskSchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  subject: z.string(),
  project: z.string().optional(),
  issue: z.string().optional(),
  type: z.string().optional(),
  color: z.string().optional(),
  is_group: z.boolean().optional().default(false),
  is_template: z.boolean().optional().default(false),
  status: z.enum(['Open', 'Working', 'Pending Review', 'Overdue', 'Template', 'Completed', 'Cancelled']).optional(),
  priority: z.enum(['Low', 'Medium', 'High', 'Urgent']).optional(),
  task_weight: z.number().optional(),
  parent_task: z.string().optional(),
  completed_by: z.string().optional(),
  completed_on: z.string().optional(),
  exp_start_date: z.string().optional(),
  expected_time: z.number().optional().default(0),
  start: z.number().int().optional(),
  exp_end_date: z.string().optional(),
  progress: z.number().optional(),
  duration: z.number().int().optional(),
  is_milestone: z.boolean().optional().default(false),
  description: z.string().optional(),
  depends_on: z.array(z.unknown()).optional(),
  depends_on_tasks: z.string().optional(),
  act_start_date: z.string().optional(),
  actual_time: z.number().optional(),
  act_end_date: z.string().optional(),
  total_costing_amount: z.number().optional(),
  total_billing_amount: z.number().optional(),
  review_date: z.string().optional(),
  closing_date: z.string().optional(),
  department: z.string().optional(),
  company: z.string().optional(),
  lft: z.number().int().optional(),
  rgt: z.number().int().optional(),
  old_parent: z.string().optional(),
  template_task: z.string().optional(),
});

export type Task = z.infer<typeof TaskSchema>;

export const TaskInsertSchema = TaskSchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type TaskInsert = z.infer<typeof TaskInsertSchema>;
