import { z } from 'zod';

export const WorkOrderSchema = z.object({
  id: z.string(),
  owner: z.string().optional(),
  creation: z.string().optional(),
  modified: z.string().optional(),
  modified_by: z.string().optional(),
  docstatus: z.number().default(0),
  naming_series: z.enum(['MFG-WO-.YYYY.-']),
  status: z.enum(['Draft', 'Submitted', 'Not Started', 'In Process', 'Stock Reserved', 'Stock Partially Reserved', 'Completed', 'Stopped', 'Closed', 'Cancelled']).default('Draft'),
  production_item: z.string(),
  item_name: z.string().optional(),
  image: z.string().optional(),
  bom_no: z.string(),
  mps: z.string().optional(),
  subcontracting_inward_order: z.string().optional(),
  subcontracting_inward_order_item: z.string().optional(),
  sales_order: z.string().optional(),
  company: z.string(),
  qty: z.number().default(1),
  project: z.string().optional(),
  track_semi_finished_goods: z.boolean().optional().default(false),
  reserve_stock: z.boolean().optional().default(false),
  max_producible_qty: z.number().optional(),
  material_transferred_for_manufacturing: z.number().optional().default(0),
  additional_transferred_qty: z.number().optional(),
  produced_qty: z.number().optional().default(0),
  disassembled_qty: z.number().optional(),
  process_loss_qty: z.number().optional(),
  source_warehouse: z.string().optional(),
  wip_warehouse: z.string().optional(),
  fg_warehouse: z.string().optional(),
  scrap_warehouse: z.string().optional(),
  transfer_material_against: z.enum(['Work Order', 'Job Card']).optional(),
  operations: z.array(z.unknown()).optional(),
  required_items: z.array(z.unknown()).optional(),
  allow_alternative_item: z.boolean().optional().default(false),
  use_multi_level_bom: z.boolean().optional().default(true),
  skip_transfer: z.boolean().optional().default(false),
  from_wip_warehouse: z.boolean().optional().default(false),
  update_consumed_material_cost_in_project: z.boolean().optional().default(true),
  planned_start_date: z.string().default('now'),
  planned_end_date: z.string().optional(),
  expected_delivery_date: z.string().optional(),
  actual_start_date: z.string().optional(),
  actual_end_date: z.string().optional(),
  lead_time: z.number().optional(),
  planned_operating_cost: z.number().optional(),
  actual_operating_cost: z.number().optional(),
  additional_operating_cost: z.number().optional(),
  corrective_operation_cost: z.number().optional(),
  total_operating_cost: z.number().optional(),
  has_serial_no: z.boolean().optional().default(false),
  has_batch_no: z.boolean().optional().default(false),
  batch_size: z.number().optional().default(0),
  description: z.string().optional(),
  stock_uom: z.string().optional(),
  material_request: z.string().optional(),
  material_request_item: z.string().optional(),
  sales_order_item: z.string().optional(),
  production_plan: z.string().optional(),
  production_plan_item: z.string().optional(),
  production_plan_sub_assembly_item: z.string().optional(),
  product_bundle_item: z.string().optional(),
  amended_from: z.string().optional(),
});

export type WorkOrder = z.infer<typeof WorkOrderSchema>;

export const WorkOrderInsertSchema = WorkOrderSchema.omit({ id: true, owner: true, creation: true, modified: true, modified_by: true });
export type WorkOrderInsert = z.infer<typeof WorkOrderInsertSchema>;
