/**
 * Entity type registry — extensible as new domain entities are added.
 * Each entity type maps to a database table and a set of namespaced actions.
 * Derived from TABLE_REGISTRY in packages/database/src/schema/_registry.ts
 */
export const ENTITY_TYPES = [
  'account-categories',
  'accounts-settings',
  'activity-costs',
  'activity-types',
  'addresses',
  'advisories',
  'advisory-evidence',
  'api-keys',
  'appointment-booking-settings',
  'approval-chains',
  'approval-decisions',
  'approval-requests',
  'approval-steps',
  'asset-events',
  'assets',
  'audit-logs',
  'authorization-controls',
  'authorization-rules',
  'bank-accounts',
  'bank-reconciliation-sessions',
  'bank-statement-lines',
  'bom-lines',
  'boms',
  'branches',
  'budget-commitments',
  'budgets',
  'buying-settings',
  'chart-of-accounts',
  'communications',
  'companies',
  'company-addresses',
  'contact-addresses',
  'contacts',
  'contracts',
  'cost-centers',
  'credit-notes',
  'crm-settings',
  'currencies',
  'currency-exchange-settings',
  'currency-exchange-settings-details',
  'currency-exchanges',
  'custom-field-sync-queue',
  'custom-field-values',
  'custom-fields',
  'customer-profiles',
  'debit-notes',
  'delivery-note-lines',
  'delivery-notes',
  'delivery-settings',
  'departments',
  'dependent-tasks',
  'depreciation-schedules',
  'designations',
  'discount-rules',
  'doc-links',
  'doc-postings',
  'employee-groups',
  'entity-attachments',
  'entity-versions',
  'entity-view-fields',
  'entity-views',
  'fiscal-periods',
  'fx-rates',
  'global-defaults',
  'goods-receipt-lines',
  'goods-receipts',
  'holiday-lists',
  'holidays',
  'incoming-call-settings',
  'intercompany-transactions',
  'inventory-trace-links',
  'issue-types',
  'item-groups',
  'item-variant-settings',
  'items',
  'journal-entries',
  'journal-lines',
  'landed-cost-allocations',
  'landed-cost-docs',
  'lot-tracking',
  'manufacturing-settings',
  'match-results',
  'meta-alias-resolution-rules',
  'meta-alias-sets',
  'meta-aliases',
  'meta-assets',
  'meta-lineage-edges',
  'meta-quality-checks',
  'meta-semantic-terms',
  'meta-term-links',
  'meta-value-aliases',
  'migration-checkpoints',
  'migration-conflict-resolutions',
  'migration-conflicts',
  'migration-jobs',
  'migration-lineage',
  'migration-merge-explanations',
  'migration-quarantine',
  'migration-reports',
  'migration-row-snapshots',
  'mutation-batches',
  'number-sequences',
  'org-usage-daily',
  'payment-allocations',
  'payment-terms',
  'payments',
  'plaid-settings',
  'pos-settings',
  'price-list-items',
  'price-lists',
  'project-template-tasks',
  'project-templates',
  'project-types',
  'project-updates',
  'project-users',
  'projects',
  'projects-settings',
  'psoa-projects',
  'purchase-invoice-lines',
  'purchase-invoices',
  'purchase-order-lines',
  'purchase-orders',
  'purchase-requests',
  'quotation-lines',
  'quotations',
  'r2-files',
  'reporting-snapshots',
  'repost-accounting-ledger-settings',
  'revenue-schedule-lines',
  'revenue-schedules',
  'role-permissions',
  'roles',
  'sales-invoice-lines',
  'sales-invoices',
  'sales-order-lines',
  'sales-orders',
  'search-documents',
  'search-outbox',
  'selling-settings',
  'service-level-agreements',
  'sites',
  'south-africa-vat-settings',
  'stock-balances',
  'stock-movements',
  'stock-reposting-settings',
  'stock-settings',
  'subscription-settings',
  'supplier-profiles',
  'support-settings',
  'tasks',
  'tax-rates',
  'timesheet-details',
  'timesheets',
  'uae-vat-settings',
  'uom',
  'uom-conversions',
  'user-roles',
  'user-scopes',
  'users',
  'video-settings',
  'voice-call-settings',
  'warehouses',
  'webhook-deliveries',
  'webhook-endpoints',
  'wip-movements',
  'work-orders',
  'workflow-definitions',
  'workflow-events-outbox',
  'workflow-executions',
  'workflow-instances',
  'workflow-outbox-receipts',
  'workflow-rules',
  'workflow-side-effects-outbox',
  'workflow-step-executions',
  'workflow-step-receipts',
] as const;

export type EntityType = (typeof ENTITY_TYPES)[number];

/**
 * Reference to a specific entity instance.
 * K-09: `id` is optional on create — kernel generates UUID.
 */
export interface EntityRef {
  type: EntityType;
  id?: string;
}

/**
 * Base fields present on every domain entity row.
 * Mirrors the `baseEntityColumns()` Drizzle helper output.
 */
export interface BaseEntity {
  id: string;
  orgId: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
  version: number;
  isDeleted: boolean;
  deletedAt: string | null;
  deletedBy: string | null;
}
