/* eslint-disable no-console, no-restricted-syntax */
/**
 * Schema barrel generator — Drizzle utilization (Phase 1)
 *
 * Auto-generates packages/database/src/schema/index.ts from schema/*.ts files.
 * Replaces 370+ lines of manual exports with a single source of truth.
 *
 * Run: pnpm db:barrel
 * Run from packages/database directory.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SCHEMA_DIR = path.resolve(__dirname, '..', 'schema');
const INDEX_FILE = path.join(SCHEMA_DIR, 'index.ts');

const SKIP_FILES = new Set(['index.ts']);

function getSchemaFiles(): string[] {
  const files = fs.readdirSync(SCHEMA_DIR);
  return files
    .filter((f) => f.endsWith('.ts') && !SKIP_FILES.has(f))
    .sort((a, b) => a.localeCompare(b));
}

function generateBarrel(): string {
  const files = getSchemaFiles();
  const lines: string[] = [
    '/**',
    ' * Schema barrel — auto-generated by pnpm db:barrel',
    ' * Do not edit manually. Run: pnpm db:barrel',
    ' */',
    '',
  ];

  for (const file of files) {
    const base = file.replace(/\.ts$/, '');
    lines.push(`export * from './${base}';`);
  }

  lines.push('');
  return lines.join('\n');
}

// ── Main ─────────────────────────────────────────────────
const content = generateBarrel();
const existing = fs.existsSync(INDEX_FILE) ? fs.readFileSync(INDEX_FILE, 'utf-8') : '';

if (content !== existing) {
  fs.writeFileSync(INDEX_FILE, content, 'utf-8');
  console.log(`✅ Generated ${INDEX_FILE} (${getSchemaFiles().length} schema files)`);
} else {
  console.log('✅ Schema barrel unchanged');
}
